<script setup lang="ts">
const api = useApi(), data = ref<any>(null), error = ref(''), notice = ref(''), busy = ref(false)
const password = ref(''), reason = ref(''), confirmRules = ref(false), confirmRights = ref(false)
async function load() { try { data.value = await api('/api/admin/arena') } catch (e) { error.value = errorMessage(e) } }
async function save() {
  if (busy.value || !data.value) return; busy.value = true; error.value = ''; notice.value = ''
  try { data.value = await api('/api/admin/arena/settings', { method: 'POST', body: { enabled: !data.value.enabled, revision: data.value.revision, password: password.value, reason: reason.value, confirm_rules: confirmRules.value, confirm_rights: confirmRights.value } }); notice.value = 'Arena setting saved. No account was subscribed or charged.' }
  catch (e) { error.value = errorMessage(e); await load() } finally { busy.value = false; password.value = '' }
}
onMounted(load)
useSeoMeta({ title: 'Automated arena administration · CardShelf', robots: 'noindex, nofollow' })
</script>
<template><header class="page-heading"><div><span class="eyebrow">AUTOMATED BATTLE</span><h1>Arena access & availability</h1><p>Collector, Collector Plus and Complimentary. Subscription billing is unchanged.</p></div><NuxtLink to="/arena" class="button secondary">Open Arena</NuxtLink></header><p v-if="error" class="alert error" role="alert">{{ error }}</p><p v-if="notice" class="alert info" role="status">{{ notice }}</p><section v-if="data" class="panel settings-panel"><p><NuxtLink to="/arena/tournaments" class="button secondary">Manage tournaments & live commentary</NuxtLink></p><h2>{{ data.enabled ? 'Automated Arena is enabled' : 'Automated Arena is disabled' }}</h2><p>Players need a verified, unexpired Live Collector / Collector Plus period or an explicit valid administrator assignment to Collector, Collector Plus or Complimentary. Complimentary accounts do not need a payment. Free accounts, general tester grants and disabled membership enforcement do not unlock battles. Administrators manage this page but do not automatically receive a player subscription.</p><p><NuxtLink to="/admin/memberships" class="text-button">Manage explicit tiers for controlled testing</NuxtLink></p><p class="alert info">This is an automated Casual Expanded format with supported EX/ex, Abilities, Tools, Stadiums and multi-step Trainers. Every card must have a completely supported profile. Special Energy and unimplemented card effects remain blocked; this is not official tournament certification. Saved Core matches retain their original rules. Original tutorial cards require no catalogue import. A provider's free data access is not publisher permission to operate a branded game.</p><form class="form-stack" @submit.prevent="save"><label>Your administrator password<input v-model="password" type="password" required autocomplete="current-password" maxlength="128" :disabled="busy"></label><label>Reason<input v-model="reason" minlength="5" maxlength="500" required :disabled="busy"></label><template v-if="!data.enabled"><label class="checkbox-label"><input v-model="confirmRules" type="checkbox" required :disabled="busy">I understand the supported format and will test with two eligible accounts before a wider launch.</label><label class="checkbox-label"><input v-model="confirmRights" type="checkbox" required :disabled="busy">I have reviewed game-data, artwork and publisher rights for this deployment.</label></template><button class="button primary" :disabled="busy || !password || reason.trim().length < 5 || (!data.enabled && (!confirmRules || !confirmRights))">{{ data.enabled ? 'Pause automated arena' : 'Enable automated arena' }}</button></form><p class="data-note">Pausing stops new gameplay without deleting saved decks or matches. The earlier assisted beta is retired. Old decks can be copied and validated in the Arena deck workshop; old matches remain archived. Advertisements remain excluded.</p></section></template>
