<script setup lang="ts">
const api = useApi(), data = ref<any>(null), query = ref(''), password = ref(''), reason = ref(''), confirmed = ref(false), rights = ref(false)
const busy = ref(false), error = ref(''), notice = ref('')
async function load() { try { data.value = await api('/api/admin/battle', { query: { q: query.value } }) } catch (e) { error.value = errorMessage(e) } }
async function save(change: any) {
  if (busy.value || !data.value) return
  busy.value = true; error.value = ''; notice.value = ''
  try { await api('/api/admin/battle/settings', { method: 'POST', body: { revision: data.value.settings.revision, password: password.value, reason: reason.value, ...change } }); notice.value = 'Battle configuration saved. Subscriptions, cards and binders are unchanged.'; await load() }
  catch (e) { error.value = errorMessage(e); await load() } finally { busy.value = false; password.value = '' }
}
onMounted(load)
useSeoMeta({ title: 'Battle beta administration · CardShelf', robots: 'noindex, nofollow' })
</script>
<template><div class="battle-ui"><header class="battle-top"><div><span class="eyebrow">PRIVATE PLAYTEST</span><h1>Battle beta administration</h1><p class="muted">Explicit access, independent of paid tiers.</p></div><NuxtLink to="/battle" class="button secondary">Open Battle</NuxtLink></header><p class="battle-intro">This is an assisted, unranked tabletop. Card effects and tournament legality are not automated. Data-provider access does not grant game or artwork rights; review those rights before allowing publisher-specific gameplay. Enabling a private beta is not legal clearance.</p>
<p v-if="error" class="alert error" role="alert">{{ error }}</p><p v-if="notice" class="alert info" role="status">{{ notice }}</p><p v-if="!data" class="loading-panel">Loading beta settings…</p>
<template v-if="data"><div class="battle-two"><section class="panel battle-card-panel battle-form"><h2>{{ data.settings.enabled ? 'Battle beta is enabled' : 'Battle beta is disabled' }}</h2><label>Confirm your administrator password<input v-model="password" type="password" autocomplete="current-password" maxlength="128" :disabled="busy"></label><label>Reason for this change<input v-model="reason" minlength="5" maxlength="500" :disabled="busy"></label><label v-if="!data.settings.enabled" class="battle-check"><input v-model="confirmed" type="checkbox" :disabled="busy"><span>I understand this is manual, unranked play and will limit access to approved testers.</span></label><label v-if="!data.settings.enabled" class="battle-check"><input v-model="rights" type="checkbox" :disabled="busy"><span>I have reviewed the game-data and artwork rights for the intended deployment.</span></label><button class="button primary" :disabled="busy || !password || reason.trim().length < 5 || (!data.settings.enabled && (!confirmed || !rights))" @click="save({ enabled: !data.settings.enabled, confirm_assisted: confirmed, confirm_rights: rights })">{{ data.settings.enabled ? 'Pause all battle access' : 'Enable private battle beta' }}</button><p class="data-note">Pausing freezes access without deleting decks or matches. Administrators are eligible when enabled; nobody else is approved automatically, including paid and existing tester accounts. No ads are placed on battle screens.</p></section>
<section class="panel battle-card-panel"><h2>Approve playtesters</h2><form class="battle-search-head" @submit.prevent="load"><label>Find an existing account<input v-model="query" type="search" maxlength="80" placeholder="Name or email"></label><button class="button secondary" :disabled="busy">Search</button></form><p class="small muted spaced">Up to 30 results. A blank search lists approved accounts. Account approvals do not enable the beta or change membership access.</p><ul class="battle-list"><li v-for="user in data.accounts" :key="user.id" class="battle-row"><div><strong>{{ user.name }}</strong><small>{{ user.email }}</small></div><span v-if="user.role === 'admin'" class="badge">Administrator</span><button v-else class="button secondary" :disabled="busy || !password || reason.trim().length < 5" @click="save({ user_id: user.id, approved: !user.approved })">{{ user.approved ? 'Revoke beta access' : 'Approve' }}</button></li></ul></section></div></template></div></template>
<style src="~/assets/css/battle.css"></style>
