<script setup lang="ts">
const api=useApi(),auth=useAuth(),data=ref<any>(null),error=ref(''),notice=ref(''),busy=ref(false),page=ref(1),search=ref('')
const selected=ref<any>(null),tier=reactive({tier:'inherit',reason:'',expiry:'',ack:false})
const account=reactive({name:'',email:'',password:'',ack:false})
const offer=reactive({plan_code:'collector',cadence:'MONTHLY',variation_id:'',amount:'',tax:'0',terms:''})
const partner=reactive({status:'approved',reward_type:'percentage',reward:'',max_payments:1,hold_days:30,terms:'',revision:0})
const payout=ref<any>(null),reference=ref(''),paidAck=ref(false),payoutRequest=ref('')
const money=(n:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(n/100)
const date=(s:any)=>s?new Date(s).toLocaleString('en-AU'):'—'
const cents=(s:string)=>{if(!/^\d+(\.\d{1,2})?$/.test(s.trim()))throw new Error('Enter an amount with at most two decimal places.');const n=Math.round(Number(s)*100);if(!Number.isSafeInteger(n))throw new Error('Amount is too large.');return n}
async function load(){error.value='';try{data.value=await api('/api/admin/billing/overview?q='+encodeURIComponent(search.value)+'&page='+page.value);if(selected.value)select(data.value.members.find((u:any)=>u.id===selected.value.id)||null)}catch(e){error.value=errorMessage(e)}}
async function action(path:string,body:any,success='Saved.'){if(busy.value)return false;busy.value=true;error.value='';notice.value='';try{await api('/api/admin/billing/'+path,{method:'POST',body});notice.value=success;await load();return true}catch(e){error.value=errorMessage(e);return false}finally{busy.value=false}}
function select(u:any){selected.value=u;tier.tier=u?.tier||'inherit';tier.reason='';tier.expiry='';tier.ack=false;const p=u?.referral_partner||data.value?.partners.find((p:any)=>p.user_id===u?.id);Object.assign(partner,{status:p?.status||'approved',reward_type:p?.reward_type||'percentage',reward:p?String(p.reward_value/100):'',max_payments:p?.max_payments||1,hold_days:p?.hold_days??30,terms:p?.terms||'',revision:p?.revision||0})}
async function saveTier(){if(!selected.value)return;await action('tiers/'+selected.value.id,{tier:tier.tier,reason:tier.reason,expires_at:tier.tier==='complimentary'||!tier.expiry?null:new Date(tier.expiry).toISOString(),revision:selected.value.revision,confirm_billing_unchanged:tier.ack},'Tier saved. Existing tester grants and Square billing were not changed.')}
async function newAccount(){if(await action('accounts',{name:account.name,email:account.email,password:account.password,confirm_no_tester_grant:account.ack},'New subscription-ready account created. Share its initial password securely.'))Object.assign(account,{name:'',email:'',password:'',ack:false})}
async function saveOffer(){try{if(await action('offers',{plan_code:offer.plan_code,cadence:offer.cadence,variation_id:offer.variation_id,amount_minor:cents(offer.amount),tax_bps:cents(offer.tax),terms:offer.terms},'Offer saved as an unpublished draft. Verify with Square before publishing.'))Object.assign(offer,{variation_id:'',amount:'',terms:''})}catch(e){error.value=errorMessage(e)}}
async function publish(o:any){if(o.published||window.confirm('Publish this recurring offer? Confirm its Square variation, tax, customer terms, cancellation and refund information have been reviewed.'))await action('offers/'+o.id,{revision:o.revision,published:!o.published,confirm_terms_reviewed:true},o.published?'Offer paused. Existing subscriptions continue unchanged.':'Square variation verified and offer published.')}
async function savePartner(){if(!selected.value)return;try{await action('partners/'+selected.value.id,{status:partner.status,reward_type:partner.reward_type,reward_value:cents(partner.reward),max_payments:partner.max_payments,hold_days:partner.hold_days,terms:partner.terms,revision:partner.revision},'Referral terms saved. The user must opt in again before new referrals qualify.')}catch(e){error.value=errorMessage(e)}}
async function cancel(s:any){if(window.confirm('Request cancellation of future Square renewals for '+s.email+'? This is NOT a refund, and does not remove complimentary or tester access.'))await action('subscriptions/'+s.id+'/cancel',{confirm:true},'Cancellation requested. Review the cancellation date and any open invoices in Square.')}
function openPayout(c:any){payout.value=c;reference.value='';paidAck.value=false;payoutRequest.value=crypto.randomUUID()}
async function recordPaid(){const c=payout.value;if(!c)return;if(await action('commissions/'+c.id+'/record-paid',{revision:c.revision,request_id:payoutRequest.value,amount_minor:c.earned_minor-c.paid_minor,external_reference:reference.value,confirm_paid:paidAck.value},'External payment recorded. CardShelf did not transfer any funds.'))payout.value=null}
onMounted(load)
useSeoMeta({title:'Membership administration · CardShelf'})
</script>
<template>
<div class="membership-page">
<header class="page-heading"><div><span class="eyebrow">PLATFORM ADMINISTRATION</span><h1>Memberships & referrals</h1><p>Manage access separately from subscription billing.</p></div><NuxtLink to="/admin/platform" class="button secondary">Requests & plan notes</NuxtLink></header>
<p v-if="error" class="alert error" role="alert">{{error}}</p><p v-if="notice" class="alert info" role="status">{{notice}}</p>
<p v-if="auth.state.value.user?.role!=='admin'" class="alert error">Administrator access is required.</p>
<template v-if="data">
<section class="panel settings-panel"><div class="section-heading"><h2>Square connection</h2><NuxtLink to="/admin/integrations/stripe" class="button secondary">Stripe integration</NuxtLink><NuxtLink to="/admin/integrations/square" class="button secondary">Manage Square connection</NuxtLink><span class="badge">{{data.environment.toUpperCase()}}</span></div><div class="membership-status-grid"><div><small>Subscription creation</small><strong>{{data.enabled?'Enabled':'Disabled'}}</strong></div><div><small>Tier enforcement</small><strong>{{data.enforcement_enabled?'Enabled':'Disabled — testing access'}}</strong></div><div><small>Credentials configured</small><strong>{{data.configured?'Yes':'No'}}</strong></div><div><small>Reconciliation heartbeat</small><strong>{{date(data.worker_seen_at)}}</strong></div></div><p class="small muted">Use Manage Square connection for encrypted OAuth setup, location selection and plan discovery. Existing environment credentials remain supported until OAuth is connected. Upgrade defaults are sandbox, billing off and enforcement off. Existing tester grants and complimentary accounts retain full access even when enforcement is enabled.</p><p class="small muted">Square is used for platform subscription invoices only. Card-sale payments remain between collectors. An Active Square subscription is not proof of a paid invoice.</p></section>
<section class="panel settings-panel spaced"><h2>People & access</h2><form class="membership-inline" @submit.prevent="page=1;load()"><label>Find a person<input v-model="search" type="search" maxlength="100" placeholder="Name or email"></label><button class="button secondary">Search</button></form><div class="membership-admin-grid"><div class="membership-member-list"><button v-for="u in data.members" :key="u.id" type="button" :class="{selected:selected?.id===u.id}" @click="select(u)"><strong>{{u.name}}</strong><span>{{u.email}}</span><small>{{u.tester_grant?'Protected tester':u.tier||'Subscription-based'}} · {{u.role}}</small></button><p v-if="!data.members.length" class="muted">No matching accounts.</p></div><div v-if="selected"><h3>{{selected.name}}</h3><p v-if="selected.tester_grant" class="alert info">This person has a protected, non-expiring tester grant. Selecting a lower tier does not remove that grant.</p><form class="membership-form" @submit.prevent="saveTier"><label>Access tier<select v-model="tier.tier"><option value="inherit">Subscription-based / inherit</option><option value="collector">Collector — manual grant</option><option value="plus">Collector Plus — manual grant</option><option value="complimentary">Complimentary — hidden full access</option></select></label><label v-if="tier.tier!=='complimentary'">Optional manual-grant expiry<input v-model="tier.expiry" type="datetime-local"></label><p v-else class="small muted">Hidden from public plans. All current features, no subscription required and no expiry. This does not make the user an administrator.</p><label>Reason for this change<input v-model="tier.reason" minlength="5" maxlength="500" required></label><label class="membership-check"><input v-model="tier.ack" type="checkbox" required><span>I understand this does not cancel existing Square invoices or start a new paid subscription.</span></label><button class="button primary" :disabled="busy">Save access tier</button></form></div><p v-else class="muted">Select a person to manage their access and referral terms.</p></div><div class="button-row spaced"><button class="button secondary" :disabled="page===1||busy" @click="page--;load()">Previous</button><span>Page {{page}}</span><button class="button secondary" :disabled="!data.has_more||busy" @click="page++;load()">Next</button></div></section>
<details class="panel settings-panel spaced"><summary>Create a subscription-ready account</summary><p class="small muted">For a NEW subscriber without a tester grant. Use the existing “Add a collector” in Data & settings to keep inviting free testers instead. Creating a person here does not subscribe or charge them.</p><form class="membership-form" @submit.prevent="newAccount"><label>Name<input v-model="account.name" required maxlength="80"></label><label>Email<input v-model="account.email" type="email" required maxlength="254" autocomplete="off"></label><label>Initial password<input v-model="account.password" type="password" minlength="12" maxlength="128" autocomplete="new-password" required></label><label class="membership-check"><input v-model="account.ack" type="checkbox" required><span>This NEW account should not receive a testing grant. Existing accounts must not be changed.</span></label><button class="button primary" :disabled="busy">Create account</button></form></details>
<section class="panel settings-panel spaced"><h2>Subscription offers</h2><p class="small muted">Map a single-phase STATIC AUD Square plan variation to Collector or Collector Plus. Use a new variation for changed terms or prices. Publishing verifies the variation; pausing only stops new subscriptions. Prices are separate from the older unpublished plan notes.</p><div class="membership-table-wrap"><table><thead><tr><th>Plan</th><th>Cadence</th><th>Base + tax</th><th>Square variation</th><th>Status</th><th>Action</th></tr></thead><tbody><tr v-for="o in data.offers" :key="o.id"><td>{{o.plan_code==='plus'?'Collector Plus':'Collector'}}</td><td>{{o.cadence}}</td><td>{{money(o.amount_minor)}} + {{o.tax_bps/100}}%</td><td><code>{{o.variation_id}}</code></td><td>{{o.published?'Published':'Draft / paused'}}</td><td><button class="button secondary" :disabled="busy||(!o.published&&!data.configured)" @click="publish(o)">{{o.published?'Pause':'Verify & publish'}}</button></td></tr></tbody></table></div><details class="spaced"><summary>Add an offer</summary><form class="membership-form spaced" @submit.prevent="saveOffer"><div class="membership-inline"><label>Plan<select v-model="offer.plan_code"><option value="collector">Collector</option><option value="plus">Collector Plus</option></select></label><label>Cadence<select v-model="offer.cadence"><option value="MONTHLY">Monthly</option><option value="ANNUAL">Annual</option></select></label></div><label>Square plan variation ID<input v-model="offer.variation_id" required maxlength="255"></label><div class="membership-inline"><label>Base price AUD<input v-model="offer.amount" inputmode="decimal" placeholder="0.00" required></label><label>Tax added (%)<input v-model="offer.tax" inputmode="decimal" required></label></div><label>Customer-facing subscription terms<textarea v-model="offer.terms" required minlength="60" maxlength="6000" rows="6" placeholder="Describe recurring invoice amount/cadence, cancellation, refund terms and operator contact details."></textarea></label><button class="button primary" :disabled="busy">Save unpublished offer</button></form></details></section>
<section class="panel settings-panel spaced"><h2>Approved referrers</h2><p class="small muted">Select a person above, set their reward and approve them. They must then accept the terms in their own Referrals page. Any edit requires a fresh opt-in; already-attributed customers keep the terms they accepted.</p><form v-if="selected" class="membership-form" @submit.prevent="savePartner"><h3>Referral terms for {{selected.name}}</h3><div class="membership-inline"><label>Status<select v-model="partner.status"><option value="approved">Approved — user must opt in</option><option value="suspended">Suspended — no new referrals</option></select></label><label>Reward method<select v-model="partner.reward_type"><option value="percentage">Percentage of eligible revenue</option><option value="fixed">Fixed AUD reward per eligible cycle</option></select></label></div><div class="membership-inline"><label>{{partner.reward_type==='percentage'?'Reward (%)':'Reward (AUD)'}}<input v-model="partner.reward" inputmode="decimal" required></label><label>First billing cycles<input v-model.number="partner.max_payments" type="number" min="1" max="120" required></label><label>Hold days<input v-model.number="partner.hold_days" type="number" min="0" max="180" required></label></div><label>Referral terms<textarea v-model="partner.terms" minlength="30" maxlength="6000" rows="5" required placeholder="Explain eligible subscriptions, reward period, hold, refunds and payout arrangements."></textarea></label><p class="small muted">Rewards exclude tax and refunds, are capped by eligible revenue, and do not deduct Square processing fees. No rewards for sandbox transactions or card sales. Complimentary/tester access itself earns no reward.</p><button class="button primary" :disabled="busy">Save approval & terms</button></form><div class="membership-table-wrap spaced"><table><thead><tr><th>Person</th><th>Reward</th><th>Eligibility</th><th>Opt-in</th></tr></thead><tbody><tr v-for="p in data.partners" :key="p.user_id"><td>{{p.name}}<br><small>{{p.email}}</small></td><td>{{p.reward_type==='percentage'?p.reward_value/100+'%':money(p.reward_value)}}</td><td>{{p.status}} · first {{p.max_payments}} cycles · {{p.hold_days}} days hold</td><td>{{p.opted_in_at&&p.opted_in_revision===p.revision?'Accepted':'Pending / opted out'}}</td></tr></tbody></table></div></section>
<section class="panel settings-panel spaced"><h2>Referral commission ledger</h2><p class="small muted">Includes Square and Stripe subscription rewards. The first production subscription across both providers determines referral eligibility.</p><p class="alert info">Manual payout recording only. Pay through your chosen external method, then record its reference here. CardShelf does not transfer money, store bank details or send payout instructions to Square.</p><p class="small muted">Approval rechecks the subscription invoice with its original payment provider. Refunds can reduce earnings after payout; negative balances require manual reconciliation. Disputed invoices remain held for operator review. The hold period starts when CardShelf first verifies payment.</p><div class="membership-table-wrap"><table><thead><tr><th>Referrer</th><th>Provider</th><th>Earned</th><th>Recorded paid</th><th>Hold until</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr v-for="c in data.commissions" :key="c.id"><td>{{c.partner_name}}<br><small>{{c.partner_email}}</small></td><td>{{c.provider==='stripe'?'Stripe':'Square'}}</td><td>{{money(c.earned_minor)}}</td><td>{{money(c.paid_minor)}}</td><td>{{date(c.eligible_at)}}</td><td>{{c.blocked?'On hold':c.earned_minor<c.paid_minor?'Refund adjustment':c.approved?'Approved':'Review required'}}</td><td><button class="button secondary" :disabled="busy||c.blocked||c.earned_minor<=c.paid_minor" @click="action('commissions/'+c.id+'/approve',{revision:c.revision,approved:!c.approved},'Invoice reconciled and approval updated.')">{{c.approved?'Revoke approval':'Recheck & approve'}}</button><button class="button secondary" :disabled="busy||!c.approved||c.blocked||c.earned_minor<=c.paid_minor" @click="openPayout(c)">Record external payment</button></td></tr></tbody></table></div><p v-if="!data.commissions.length" class="muted">No production subscription commissions recorded.</p><form v-if="payout" class="membership-form spaced" @submit.prevent="recordPaid"><h3>Record {{money(payout.earned_minor-payout.paid_minor)}} paid to {{payout.partner_name}}</h3><label>External payment reference<input v-model="reference" required minlength="3" maxlength="200" placeholder="Reference only — no bank account numbers"></label><label class="membership-check"><input v-model="paidAck" type="checkbox" required><span>I have ALREADY paid this amount outside CardShelf. This records that completed payment, not a transfer request.</span></label><div class="button-row"><button class="button primary" :disabled="busy">Record completed payment</button><button type="button" class="button secondary" :disabled="busy" @click="payout=null">Cancel</button></div></form></section>
<details class="panel settings-panel spaced"><summary>Square subscriptions & reconciliation</summary><div class="membership-table-wrap spaced"><table><thead><tr><th>Account</th><th>Plan / status</th><th>Paid until (exclusive)</th><th>Cancellation</th><th>Actions</th></tr></thead><tbody><tr v-for="s in data.subscriptions" :key="s.id"><td>{{s.email}}<p v-if="s.last_error" class="small">{{s.last_error}}</p></td><td>{{s.plan_code}} · {{s.status}}</td><td>{{s.paid_through||'No verified paid period'}}</td><td>{{s.canceled_date||'Not scheduled'}}</td><td><button class="button secondary" :disabled="busy||!data.configured" @click="action('subscriptions/'+s.id+'/sync',{},'Square records refreshed.')">Reconcile</button><button v-if="s.current" class="button secondary" :disabled="busy||!data.configured" @click="cancel(s)">Cancel renewals</button></td></tr></tbody></table></div><h3 class="spaced">Webhook queue</h3><p class="small muted">Signed events are processed from a durable queue. Unrelated merchant transactions cannot create subscriptions or commissions here.</p><div v-for="e in data.events" :key="e.event_id" class="membership-record"><div><strong>{{e.event_type}} · {{e.status}}</strong><p class="small muted">{{e.last_error||'Waiting for reconciliation'}} · attempts {{e.attempts}}</p></div><button class="button secondary" :disabled="busy" @click="action('events/'+e.event_id,{},'Webhook queued for retry.')">Retry</button></div></details>
</template></div>
</template>
<style src="~/assets/css/membership.css"></style>
