<script setup lang="ts">
const api=useApi(),notice=useNotice(),data=ref<any>(null),error=ref(''),busy=ref(false),page=ref(1)
const pages=computed(()=>Math.max(1,Math.ceil((data.value?.counts.requests||0)/50)))
async function load(){error.value='';try{data.value=await api('/api/admin/platform',{query:{page:page.value,view:'requests'}})}catch(e){error.value=errorMessage(e)}}
onMounted(load)
async function status(request:any,next:string){if(busy.value)return;busy.value=true;try{await api('/api/admin/platform/requests/'+request.id,{method:'PATCH',body:{status:next,revision:request.revision}});await load()}catch(e){notice.show(errorMessage(e),'error')}finally{busy.value=false}}
async function remove(request:any){if(busy.value||!confirm('Delete this request and its contact details? This does not delete a user account.'))return;busy.value=true;try{await api('/api/admin/platform/requests/'+request.id,{method:'DELETE',body:{revision:request.revision}});await load()}catch(e){notice.show(errorMessage(e),'error')}finally{busy.value=false}}
async function changePage(next:number){page.value=next;await load()}
useSeoMeta({title:'Platform administration · CardShelf'})
</script>
<template><NuxtLink to="/admin" class="text-button back-link"><AppIcon name="left" :size="16" />Administration</NuxtLink><header class="page-heading"><div><span class="eyebrow">PLATFORM ADMINISTRATION</span><h1>Website requests</h1><p>Review access, support and privacy requests in one inbox.</p></div><button class="button secondary" :disabled="busy" @click="load"><AppIcon name="refresh" :size="17" />Refresh</button></header><p v-if="error" class="alert error">{{error}}</p><p v-if="!data&&!error" class="loading-panel">Loading platform information…</p><template v-if="data"><section class="panel platform-admin-panel"><div class="section-heading"><div><h2>Requests to review</h2><p>Access, support and privacy requests from the website. No emails are sent automatically.</p></div><span class="badge purple">{{data.counts.new_requests}} new</span></div><article v-for="request in data.requests" :key="request.id" class="platform-request"><div class="request-header"><div><strong>{{request.name}}</strong><p class="small muted">{{request.email}} · {{request.purpose==='early_access'?'account access':request.purpose}}</p></div><span class="badge" :class="request.status==='new'?'purple':''">{{request.status}}</span></div><p>{{request.message||'No additional message.'}}</p><div class="button-row"><button class="button secondary small-button" :disabled="busy||request.status==='contacted'" @click="status(request,'contacted')">Mark contacted</button><button class="button secondary small-button" :disabled="busy||request.status==='archived'" @click="status(request,'archived')">Archive</button><button class="text-button danger-text" :disabled="busy" @click="remove(request)">Delete contact request</button></div></article><p v-if="!data.requests.length" class="platform-admin-empty">No requests on this page.</p><p class="data-note">Create new public members through Free tier administration, or use Memberships & referrals for a subscription-ready account. Add a collector in Data & settings preserves the legacy tester workflow. Marking a request contacted does not create an account.</p><NuxtLink to="/admin/free-platform" class="text-button">Open account administration<AppIcon name="arrow" :size="16" /></NuxtLink></section><div class="platform-pagination"><button class="button secondary" :disabled="page<=1||busy" @click="changePage(page-1)">Previous</button><span>Page {{page}} of {{pages}} · up to 50 requests per page</span><button class="button secondary" :disabled="page>=pages||busy" @click="changePage(page+1)">Next</button></div></template></template>
