<script setup lang="ts">
const api=useApi(),notice=useNotice(),data=ref<any>(null),error=ref(''),busy=ref(false)
const drafts=reactive<Record<string,any>>({})
async function load(){error.value='';try{data.value={plans:await api('/api/admin/platform/plans')};for(const p of data.value.plans){drafts[p.code]={...p,monthly:p.monthly_price_minor==null?'':(p.monthly_price_minor/100).toFixed(2),annual:p.annual_price_minor==null?'':(p.annual_price_minor/100).toFixed(2)}}}catch(e){error.value=errorMessage(e)}}
onMounted(load)
function cents(value:string){const text=String(value).trim();if(!text)return null;if(!/^\d+(?:\.\d{1,2})?$/.test(text))throw new Error('Enter an AUD amount with at most two decimal places.');const [whole,fraction='']=text.split('.');return Number(whole)*100+Number(fraction.padEnd(2,'0'))}
async function savePlan(code:string){if(busy.value)return;busy.value=true;try{const p=drafts[code];await api('/api/admin/platform/plans/'+code,{method:'PUT',body:{name:p.name,description:p.description,monthly_price_minor:cents(p.monthly),annual_price_minor:cents(p.annual),revision:p.revision}});notice.show('Draft saved.');await load()}catch(e){notice.show(errorMessage(e),'error')}finally{busy.value=false}}
useSeoMeta({title:'Pricing & plans · CardShelf'})
</script>
<template><div><header class="page-heading"><div><span class="eyebrow">PLANS & BILLING</span><h1>Pricing & plans</h1><p>Review Free alongside your Stripe membership products.</p></div></header><div class="button-row spaced"><NuxtLink to="/admin/integrations/stripe-preview" class="button primary">Test pricing preview</NuxtLink><NuxtLink to="/pricing" class="button secondary">Public pricing</NuxtLink><NuxtLink to="/admin/scanning#tier-limits" class="button secondary">Tier scan limits</NuxtLink></div><section class="panel settings-panel spaced"><h2>Free · $0 forever</h2><p>Free is managed by CardShelf and appears automatically on public pricing and the Test preview. It does not need a Stripe product.</p><p class="muted small">Public catalogue and marketplace browsing, card artwork and available source prices. Collection management and photo scanning require eligible membership access.</p><NuxtLink to="/admin/free-platform" class="text-button">Free registration & sponsors<AppIcon name="arrow" :size="16"/></NuxtLink></section><StripeProductSync @synced="load"/><p v-if="error" class="alert error">{{error}}</p><details v-if="data" class="panel settings-panel spaced"><summary>Advanced: plan mirror & private drafts</summary><section><h2>Platform plan details</h2><p class="muted small">Enable the Live plan mirror above to populate these details from Stripe. Synced plans are read-only; optional unsynced drafts remain private planning notes. Automatic-tax amounts are base/display prices, not a tax quote.</p><div class="platform-admin-plans"><form v-for="plan in data.plans.filter((p:any)=>p.state==='draft')" :key="plan.code" class="panel platform-admin-panel form-stack" @submit.prevent="savePlan(plan.code)"><span class="badge">{{plan.code}} · {{plan.stripe_managed?'Synced from Stripe':'Private draft'}}</span><fieldset :disabled="plan.stripe_managed" style="border:0;padding:0;margin:0;display:contents"><label>Plan name<input v-model="drafts[plan.code].name" required maxlength="80" /></label><label>Description<textarea v-model="drafts[plan.code].description" maxlength="500" /></label><div class="form-columns"><label>Monthly price · AUD<input v-model="drafts[plan.code].monthly" inputmode="decimal" placeholder="Not decided" /></label><label>Annual price · AUD<input v-model="drafts[plan.code].annual" inputmode="decimal" placeholder="Not decided" /></label></div></fieldset><p v-if="plan.stripe_managed" class="small muted">Update this product in Stripe; the daily or manual sync refreshes it here.</p><button v-else class="button secondary" :disabled="busy">Save draft only</button></form></div></section></details></div></template>
