<template>
  <section class="m-container m-section"><h2>Free accounts, public card data and sponsor placements</h2>
    <p>The reference catalogue can be read without signing in. Account email addresses, private quantities, notes and binder contents are not included in its responses. Newly registered Free accounts do not receive protected tester access; subscriptions and explicit administrative grants are separate.</p>
    <p>When enabled by the administrator, signed-in Free accounts may see a clearly labelled first-party sponsor placement. CardShelf checks eligibility on the server. Paid accounts, testers, Complimentary users and signed-out visitors do not receive these placements. First-party sponsorship does not add advertising cookies or tracking scripts. The selected advertising provider, Google AdSense (including Auto ads) or Adsterra (banner and native placements), may show ads to signed-out visitors on the homepage, features, pricing and public catalogue/details, and to eligible Free accounts on approved signed-in content pages. These placements may load the selected provider and its advertising partners, use cookies or other identifiers, and process IP addresses, device information, page URLs, rendered page content and advertising/consent signals according to the published privacy messages. Paid and protected accounts are excluded from the CardShelf advertising loader. Password, billing, account-administration, private-message, private card-editor, binder and battle screens are excluded. Signing out or losing eligibility replaces a document that loaded advertising; returning to a private editor first opens an ad-free document. Free users may browse sale listings but need the appropriate membership to start enquiries or sell. Following a sponsor's link opens an external website with its own privacy practices.</p>
    <p>CardShelf stores uploaded sponsor artwork locally after re-encoding it. Public card artwork for additional games is likewise cached on this server; existing Pokémon artwork still uses the configured catalogue provider. Ordinary server access logs and essential session cookies continue to apply. Email-based password recovery sends a short-lived one-time link through the configured Postal or external SMTP mail service. Only token hashes are stored; successful redemption revokes old sessions. Queued email metadata is retained briefly for delivery and troubleshooting. Account email verification is not included.</p>
    <p>For Google advertising, see <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener noreferrer">how Google uses information from sites that use its services</a>. Use the published Google consent message and its privacy-options link to review or withdraw consent. CardShelf does not treat declining consent as a subscription purchase or removal of account access.</p>
    <p>For Adsterra advertising, see <a href="https://adsterra.com/privacy-policy/" target="_blank" rel="noopener noreferrer">Adsterra’s privacy policy</a>. Adsterra and Google are separate providers; Google privacy controls do not configure Adsterra.</p>
    <CatalogueCredits />
  </section>
</template>
