<template>
  <section class="m-container m-section"><h2>Free accounts, public card data and sponsor placements</h2>
    <p>The reference catalogue can be read without signing in. Account email addresses, private quantities, notes and binder contents are not included in its responses. Newly registered Free accounts do not receive protected tester access; subscriptions and explicit administrative grants are separate.</p>
    <p>When enabled by the administrator, signed-in Free accounts may see a clearly labelled first-party sponsor placement. CardShelf checks eligibility on the server. Paid accounts, testers, Complimentary users and signed-out visitors do not receive these placements. First-party sponsorship does not add advertising cookies or tracking scripts. Separately enabled Google AdSense on public catalogue pages may load Google and its advertising partners, use cookies or other identifiers, and process IP addresses, device information, page URLs and advertising/consent signals according to the published privacy messages. Paid and protected accounts are excluded from the CardShelf AdSense loader. Following a sponsor's link opens an external website with its own privacy practices.</p>
    <p>CardShelf stores uploaded sponsor artwork locally after re-encoding it. Public card artwork for additional games is likewise cached on this server; existing Pokémon artwork still uses the configured catalogue provider. Ordinary server access logs and essential session cookies continue to apply. Email-based password recovery sends a short-lived one-time link through the configured SMTP provider. Only token hashes are stored; successful redemption revokes old sessions. Queued email metadata is retained briefly for delivery and troubleshooting. Account email verification is not included.</p>
    <p>For Google advertising, see <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener noreferrer">how Google uses information from sites that use its services</a>. Use the published Google consent message and its privacy-options link to review or withdraw consent. CardShelf does not treat declining consent as a subscription purchase or removal of account access.</p>
    <CatalogueCredits />
  </section>
</template>
