<script setup lang="ts">
import { productGroups, productPresentation, offerTaxLabel } from '../../shared/stripe-products.mjs'
import { pricingFeatures } from '../../shared/pricing-table.mjs'
const brokenImages=reactive<Record<string,boolean>>({})
const props=defineProps<{free:boolean}>(),emit=defineEmits<{updated:[]}>()
const api=useApi(),route=useRoute(),data=ref<any>(null),error=ref(''),notice=ref(''),busy=ref(false),chosen=ref(''),consent=ref(false),intent=ref('')
const referral=ref(typeof route.query.ref==='string'?route.query.ref:''),referralConsent=ref(false)
const groups=computed(()=>productGroups(data.value?.offers||[]).map(group=>({...group,features:pricingFeatures(group.product.marketing_features)})))
const selected=computed(()=>data.value?.offers.find((o:any)=>o.id===chosen.value))
const pending=computed(()=>data.value?.subscriptions.some((s:any)=>s.current||new Date(s.paid_through).getTime()>Date.now()))
const money=(n:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(n/100)
const date=(s:string)=>s?new Date(s).toLocaleString('en-AU'):'Awaiting verified payment'
async function load(){try{data.value=await api<any>('/api/billing/stripe/account');if(!chosen.value){chosen.value=data.value.offers.find((o:any)=>o.plan_code===route.query.plan&&o.cadence===route.query.cadence)?.id||''}}catch(e){error.value=errorMessage(e)}}
async function run(task:()=>Promise<any>){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{const r=await task();await load();emit('updated');return r}catch(e){error.value=errorMessage(e)}finally{busy.value=false}}
function navigate(url:string,host:string){const u=new URL(url);if(u.protocol!=='https:'||u.hostname!==host||u.username||u.password)throw new Error('Unexpected payment destination.');window.location.assign(u.href)}
async function subscribe(s:any=null){const o=s?.offer_snapshot||selected.value;if(!o||props.free||(!s&&!consent.value))return;intent.value||=crypto.randomUUID();await run(async()=>{
  if(!s&&referral.value.trim()){if(!referralConsent.value)throw new Error('Confirm the referral disclosure or clear its code.');await api('/api/referrals/claim',{method:'POST',body:{code:referral.value.trim(),consent:true}})}
  const r=await api<any>('/api/billing/stripe/checkout',{method:'POST',body:{offer_id:o.id,revision:o.revision,terms_hash:o.terms_hash,request_id:s?.request_id||intent.value,consent:true}})
  if(r.url)navigate(r.url,'checkout.stripe.com');else notice.value='Checkout is awaiting confirmation. Refresh or retry the original request; do not create another subscription.'
})}
async function portal(){await run(async()=>{const r=await api<any>('/api/billing/stripe/portal',{method:'POST',body:{}});navigate(r.url,'billing.stripe.com')})}
async function cancel(s:any){if(!window.confirm(s.confirmed?'Cancel Stripe renewals at the end of this billing period? This is not a refund.':'Expire this unpaid checkout? A completed checkout must be managed as a subscription.'))return;await run(()=>api(`/api/billing/stripe/${s.id}/cancel`,{method:'POST',body:{confirm:true}}))}
watch(chosen,()=>{intent.value='';consent.value=false})
onMounted(load)
</script>
<template><section v-if="data" class="panel settings-panel spaced stripe-membership">
<div class="section-heading"><div><span class="eyebrow">SECURE SUBSCRIPTIONS</span><h2>Pay with Stripe</h2></div><span class="badge">{{data.environment==='production'?'LIVE':'TEST MODE'}}</span></div>
<p class="muted">Subscribe on Stripe’s secure checkout and manage your payment method, invoices and cancellation through its customer portal. Existing subscriptions and checkout links are managed below; a paused sign-up screen does not cancel recurring payments.</p>
<p v-if="error" class="alert error" role="alert">{{error}}</p><p v-if="notice" class="alert info" role="status">{{notice}}</p>
<p v-if="free" class="alert info">Your testing or complimentary access is protected. No payment is needed.</p>
<p v-else-if="!data.enabled" class="muted">Stripe is not accepting new subscriptions. Existing subscriptions and billing management remain separate.</p>
<p v-else-if="pending" class="alert info">You already have a subscription or pending Stripe checkout. Manage it below instead of starting another.</p>
<template v-else><p v-if="!data.offers.length" class="muted">No Stripe plans are available yet.</p><div class="membership-products"><fieldset v-for="group in groups" :key="group.code" class="membership-product"><legend>{{group.product.name||(group.code==='plus'?'Collector Plus':'Collector')}}</legend><img v-if="group.product.images[0]&&!brokenImages[group.code]" :src="group.product.images[0]" :alt="group.product.name" width="64" height="64" referrerpolicy="no-referrer" @error="brokenImages[group.code]=true"><p class="product-description">{{group.product.description}}</p><ul v-if="group.features.length"><li v-for="(feature,index) in group.features" :key="index">{{feature.name}}</li></ul><PlanScanAllowance :plan-code="group.code" :allowances="data.scan_allowances" /><div class="membership-offers"><label v-for="o in group.offers" :key="o.id" class="membership-offer" :class="{selected:chosen===o.id}"><input v-model="chosen" type="radio" :value="o.id" :disabled="busy"><span><strong>{{o.cadence==='MONTHLY'?'Monthly':'Yearly'}}</strong><b>{{money(o.total_minor)}} / {{o.cadence==='MONTHLY'?'month':'year'}}<template v-if="group.product.unit_label"> / {{group.product.unit_label}}</template></b><small>{{offerTaxLabel(o)}}</small></span></label></div></fieldset></div>
<form v-if="selected" class="membership-form" @submit.prevent="subscribe()"><pre class="membership-terms">{{selected.terms}}</pre><label>Referral code (optional)<input v-model="referral" maxlength="24" autocomplete="off"></label><label v-if="referral.trim()" class="membership-check"><input v-model="referralConsent" type="checkbox" required><span>I agree that the approved referrer may earn a commission on my subscription.</span></label><label class="membership-check"><input v-model="consent" type="checkbox" required><span>I accept the terms and recurring {{money(selected.total_minor)}} {{selected.cadence==='MONTHLY'?'monthly':'annual'}} charge until cancellation<template v-if="selected.tax_mode==='automatic'&&selected.tax_behavior==='exclusive'">, plus applicable tax confirmed by Stripe at checkout</template>.</span></label><button class="button primary" :disabled="busy||!consent">{{data.environment==='sandbox'?'Open test checkout':'Continue to Stripe'}}</button></form></template>
<article v-for="s in data.subscriptions" :key="s.id" class="membership-history"><div><strong>{{productPresentation(s.offer_snapshot.product_snapshot).name||(s.offer_snapshot.plan_code==='plus'?'Collector Plus':'Collector')}}</strong> <span class="badge">{{s.status}}</span><p>{{money(s.offer_snapshot.total_minor)}} / {{s.offer_snapshot.cadence==='MONTHLY'?'month':'year'}} · {{offerTaxLabel(s.offer_snapshot)}}</p><p class="small">Verified paid access: {{date(s.paid_through)}}<br><span v-if="s.cancel_at_period_end">Future renewal is cancelled.</span></p><p v-if="s.last_error" class="alert error">{{s.last_error}}</p></div><div class="button-row"><a v-if="s.checkout_url&&new Date(s.checkout_expires_at).getTime()>Date.now()" :href="s.checkout_url" class="button primary" rel="noreferrer">Resume Stripe checkout</a><button v-if="s.status==='pending'" class="button secondary" :disabled="busy" @click="subscribe(s)">Retry original checkout</button><button class="button secondary" :disabled="busy" @click="run(()=>api(`/api/billing/stripe/${s.id}/sync`,{method:'POST',body:{}}))">Refresh status</button><button v-if="s.confirmed" class="button secondary" :disabled="busy" @click="portal">Manage Stripe billing</button><button v-if="s.current&&!s.cancel_at_period_end" class="button secondary" :disabled="busy" @click="cancel(s)">{{s.confirmed?'Cancel renewals':'Cancel checkout'}}</button></div></article>
<p v-if="data.environment==='sandbox'" class="small muted">Test mode: use Stripe test payment details only. Returning from checkout does not itself confirm payment.</p>
</section></template>
<style scoped>
.membership-products{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;margin:20px 0}.membership-product{min-width:0;border:1px solid #dfe3ec;border-radius:16px;padding:20px}.membership-product legend{font-size:20px;font-weight:700;padding:0 8px}.membership-product img{object-fit:contain;float:right;margin:0 0 12px 12px;border-radius:12px}.product-description{white-space:pre-line;overflow-wrap:anywhere}.membership-product ul{padding-left:20px}.membership-product li{margin:7px 0;overflow-wrap:anywhere}.membership-product .membership-offers{grid-template-columns:1fr}.membership-product .membership-offer{width:100%}@media(max-width:700px){.membership-products{grid-template-columns:1fr}}
</style>
