import test from 'node:test';
import assert from 'node:assert/strict';
import {generationInput,makeBinderPlan,previewResult} from '../lib/binder-generation-logic.mjs';
const sets=[{id:'en:one',name:'First set',language:'en',series:'Example series',release_date:'2020-01-01',card_count:3,imported_count:3}];
const input={title:'My series',set_ids:['en:one'],columns:3,rows:3,color:'#5546d8'};
const row=(n,key='normal',quantity=0)=>({printing_id:`p${n}-${key}`,key,source:'tcgdex',label:key,card_id:'en:one-'+n,name:'Card '+n,local_id:String(n),set_id:'en:one',quantity});
const plan=(options={},rows=[row(10),row(2),row(1)])=>makeBinderPlan(generationInput({...input,...options}),sets,rows);
test('generator validates chosen sets and rejects arbitrary input',()=>{for(const set_ids of [[],null,['https://evil.test'],['en:a','ja:b'],Array(51).fill('en:one')])assert.throws(()=>generationInput({...input,set_ids}));});
test('selected set IDs are deduplicated and deterministically ordered',()=>assert.deepEqual(generationInput({...input,set_ids:['en:z','en:a','en:z']}).set_ids,['en:a','en:z']));
test('collector numbers sort naturally rather than lexicographically',()=>assert.deepEqual(plan().volumes[0].slots.map(s=>s.local_id),['1','2','10']));
test('one design per card prefers normal then holo then reverse',()=>{const p=plan({},[row(1,'reverse'),row(1,'holo'),row(1),row(2,'holo')]);assert.deepEqual(p.volumes[0].slots.map(s=>s.printing_id),['p1-normal','p2-holo']);});
test('all known printing mode keeps separate finishes',()=>assert.equal(plan({selection:'printings'},[row(1),row(1,'holo')]).slot_count,2));
test('owned-only uses an owned printing, never a missing preferred finish',()=>{const p=plan({owned_only:true},[row(1),row(1,'reverse',4)]);assert.equal(p.slot_count,1);assert.equal(p.owned_slots,1);assert.equal(p.volumes[0].slots[0].printing_id,'p1-reverse');});
test('duplicate owned copies do not generate duplicate pockets',()=>assert.equal(plan({owned_only:true},[row(1,'normal',12)]).slot_count,1));
test('empty owned-only layouts give a helpful error',()=>assert.throws(()=>plan({owned_only:true}),/No owned cards/));
test('full-set layout includes missing cards without creating ownership',()=>{const rows=[row(1),row(2,'normal',1)];const original=structuredClone(rows);const p=plan({},rows);assert.equal(p.slot_count,2);assert.equal(p.owned_slots,1);assert.deepEqual(rows,original);});
test('partial imports are explicitly reported in the preview',()=>{const p=makeBinderPlan(generationInput(input),[{...sets[0],imported_count:2}],[row(1),row(2)]);assert.equal(previewResult(p).partial,true);});
test('unimported selected sets cannot silently disappear',()=>assert.throws(()=>makeBinderPlan(generationInput({...input,set_ids:['en:one','en:missing']}),sets,[row(1)]),/not imported/));
test('page count is calculated from pockets, not hard coded',()=>{const p=plan({columns:2,rows:2},Array.from({length:5},(_,i)=>row(i+1)));assert.equal(p.volumes[0].page_count,2);});
test('layouts larger than 60 pages split into numbered binders',()=>{const p=plan({},Array.from({length:541},(_,i)=>row(i+1)));assert.equal(p.volumes.length,2);assert.equal(p.volumes[0].page_count,60);assert.equal(p.volumes[1].page_count,1);assert.equal(p.volumes[1].slots[0].position,0);assert.equal(p.volumes[0].title,'My series · 1/2');});
test('new-page-per-set reserves only the required inter-set gaps',()=>{const second={...sets[0],id:'en:two',name:'Second set',release_date:'2021-01-01'};const rows=[row(1),{...row(2),set_id:'en:two'}];const opts=generationInput({...input,set_ids:['en:one','en:two']});const p=makeBinderPlan(opts,[second,...sets],rows);assert.deepEqual(p.volumes[0].slots.map(s=>s.position),[0,9]);});
test('compact multi-set layout does not reserve inter-set gaps',()=>{const second={...sets[0],id:'en:two',name:'Second set',release_date:'2021-01-01'};const opts=generationInput({...input,set_ids:['en:one','en:two'],new_page_per_set:false});const p=makeBinderPlan(opts,[second,...sets],[row(1),{...row(2),set_id:'en:two'}]);assert.deepEqual(p.volumes[0].slots.map(s=>s.position),[0,1]);});
test('preview tokens change when a selected printing or ownership status changes',()=>{const first=plan({},[row(1)]);assert.notEqual(first.token,plan({},[row(2)]).token);assert.notEqual(first.token,plan({},[row(1,'normal',1)]).token);assert.equal(first.token,plan({},[row(1)]).token);});
test('over-limit series selections fail without partial binder creation',()=>assert.throws(()=>plan({columns:2,rows:2},Array.from({length:2401},(_,i)=>row(i+1))),/more than 10 binders/));
test('preview samples report human-readable page and pocket positions',()=>{const p=previewResult(plan());assert.equal(p.sample[0].volume,1);assert.equal(p.sample[0].page,1);assert.equal(p.sample[0].pocket,1);});
