import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import { parse, compileScript } from '@vue/compiler-sfc';
import { MORE_GROUPS, ADMIN_LINKS, administrationLinks, activeNavigation } from '../shared/navigation.mjs';
const read = file => fs.readFileSync(new URL('../' + file, import.meta.url), 'utf8');
const plain = value => JSON.parse(JSON.stringify(value));
function ui(file, api = async () => ({}), role = 'admin') {
  const script = read(file).match(/<script setup lang="ts">([\s\S]*?)<\/script>/)[1].replace(/^import .*$/mg, '');
  const ast = ts.createSourceFile(file, script, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS), names = [], unmounts = [];
  const add = node => { if (ts.isIdentifier(node)) names.push(node.text); else if (ts.isObjectBindingPattern(node) || ts.isArrayBindingPattern(node)) for (const entry of node.elements) if (ts.isBindingElement(entry)) add(entry.name); };
  for (const node of ast.statements) { if (ts.isVariableStatement(node)) for (const declaration of node.declarationList.declarations) add(declaration.name); if (ts.isFunctionDeclaration(node) && node.name) names.push(node.name.text); }
  const js = ts.transpileModule(script, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext } }).outputText;
  const scope = { ref: value => ({ value }), reactive: value => value, computed: fn => ({ get value() { return fn(); } }), onMounted() {}, onBeforeUnmount: fn => unmounts.push(fn), nextTick: fn => fn(), useApi: () => api, useAuth: () => ({ state: { value: { user: { role } } } }), useSeoMeta() {}, errorMessage: error => error.data?.message || error.message || 'Request failed', URL, Date, Number, document: { getElementById: () => null }, console };
  return { ...vm.runInNewContext('(function(){' + js + '; return {' + names.join(',') + '};})()', scope), unmounts };
}
const admin = 'app/pages/admin/emails.vue', personal = 'app/pages/emails.vue';
const settings = extra => ({ exists: true, enabled: true, configured: true, origin: 'https://postal.cardshelf.cloud', sender_name: 'CardShelf', from_address: 'noreply@cardshelf.cloud', reply_to: 'support@cardshelf.cloud', api_key_set: true, key_available: true, revision: 2, dkim_selector: '', dkim_public_key: '', webhook_public_key: '', ...extra });
const overview = extra => ({ settings: settings(), counts: [], recent: [], suppressions: [], ...extra });
test('More exposes personal preferences and separately role-restricted email administration', () => { assert.ok(MORE_GROUPS.flatMap(group => group.links).some(link => link.to === '/emails')); assert.ok(ADMIN_LINKS.some(link => link.to === '/admin/emails' && link.label === 'Emails')); assert.ok(!administrationLinks('user').some(link => link.to === '/admin/emails')); assert.equal(activeNavigation('/emails'), 'more'); assert.equal(activeNavigation('/admin/emails'), 'more'); });
test('first preference save accepts revision zero and posts only the supported optional groups', async () => { const calls = [], h = ui(personal, async (url, options) => { calls.push({ url, options }); return options ? { marketplace: true, membership: false, revision: 1 } : { marketplace: false, membership: false, revision: 0 }; }); await h.load(); assert.equal(h.ready.value, true); h.preferences.marketplace = true; await h.save(); assert.deepEqual(plain(calls[1].options.body), { marketplace: true, membership: false, revision: 0 }); assert.equal(h.preferences.revision, 1); });
test('preference concurrency conflict retains local choices and requires an explicit reload', async () => { const h = ui(personal, async (url, options) => { if (options) throw { statusCode: 409, message: 'Email preferences changed.' }; return { marketplace: false, membership: false, revision: 3 }; }); await h.load(); h.preferences.marketplace = true; await h.save(); assert.equal(h.conflict.value, true); assert.equal(h.preferences.marketplace, true); await h.load(); assert.equal(h.conflict.value, false); assert.equal(h.preferences.marketplace, false); });
test('non-administrator page does not fetch the administrative overview', async () => { let calls = 0; const h = ui(admin, async () => { calls++; }, 'user'); await h.load(); assert.equal(calls, 0); assert.equal(h.data.value, null); });
test('loading public credential state never copies an API key or password into its form', async () => { const h = ui(admin, async () => overview({ settings: settings({ api_key: 'SERVER-MUST-NEVER-RETURN-THIS', secret: 'SECRET' }) })); h.setup.api_key = 'local-old-key'; h.setup.password = 'old-password'; await h.load(); assert.equal(h.setup.api_key, ''); assert.equal(h.setup.password, ''); assert.equal(h.setup.revision, 2); assert.equal(h.setup.secret, undefined); });
test('blank API credential is sent unchanged to retain it and settings save clears password', async () => { let sent; const h = ui(admin, async (url, options) => { if (options) { sent = plain(options.body); return settings({ revision: 3 }); } return overview(); }); await h.load(); h.setup.password = 'current'; await h.save(); assert.equal(sent.api_key, ''); assert.equal(sent.clear_api_key, false); assert.equal(sent.revision, 2); assert.equal(sent.password, 'current'); assert.equal(h.setup.password, ''); });
test('explicit credential removal never also sends a replacement key', async () => { let sent; const h = ui(admin, async (url, options) => { if (options) { sent = plain(options.body); return settings({ enabled: false, api_key_set: false, revision: 3 }); } return overview(); }); await h.load(); h.setup.api_key = 'new-key'; h.setup.clear_api_key = true; h.setup.password = 'current'; await h.save(); assert.equal(sent.api_key, ''); assert.equal(sent.clear_api_key, true); assert.equal(h.setup.api_key, ''); });
test('secret inputs are cleared after a failed save and unmount, with no secret browser storage', async () => { const h = ui(admin, async (url, options) => { if (options) throw { statusCode: 403, message: 'Confirm password.' }; return overview(); }); await h.load(); h.setup.password = 'password'; h.setup.api_key = 'temporary-secret'; await h.save(); assert.equal(h.setup.password, ''); assert.equal(h.setup.api_key, ''); h.setup.api_key = 'next-secret'; h.testPassword.value = 'password'; h.unmounts.forEach(fn => fn()); assert.equal(h.setup.api_key, ''); assert.equal(h.testPassword.value, ''); assert.equal(h.data.value, null); assert.doesNotMatch(read(admin), /localStorage|sessionStorage/); });
test('a settings conflict requires reload while incomplete configuration can still be corrected', async () => { for (const [message, conflict] of [['Email settings changed. Reload before saving.', true], ['Save a valid Postal API key before enabling email.', false]]) { const h = ui(admin, async (url, options) => { if (options) throw { statusCode: 409, message }; return overview(); }); await h.load(); h.setup.password = 'password'; await h.save(); assert.equal(h.conflict.value, conflict); } });
test('Postal console links allow only credential-free HTTPS origins from server settings', async () => { const h = ui(admin); for (const [origin, expected] of [['https://postal.cardshelf.cloud', 'https://postal.cardshelf.cloud'], ['javascript:alert(1)', ''], ['http://postal.cardshelf.cloud', ''], ['https://user:secret@postal.cardshelf.cloud', '']]) { h.data.value = overview({ settings: settings({ origin }) }); assert.equal(h.postalConsole.value, expected); } });
test('DNS lookups only occur after the explicit check action, never initial load', async () => { const calls = [], h = ui(admin, async url => { calls.push(url); return url.endsWith('/diagnostics') ? { checks: [], notice: 'No guarantee' } : overview(); }); await h.load(); assert.deepEqual(calls, ['/api/admin/emails']); await h.checkDns(); assert.equal(calls[1], '/api/admin/emails/diagnostics'); });
test('test email sends only an administrator password and cannot choose arbitrary recipients', async () => { let sent; const h = ui(admin, async (url, options) => { if (options) { sent = { url, body: plain(options.body) }; return { message: 'Queued' }; } return overview(); }); await h.load(); h.testPassword.value = 'current'; await h.sendTest(); assert.deepEqual(sent, { url: '/api/admin/emails/test', body: { password: 'current' } }); assert.equal(h.testPassword.value, ''); });
test('retry affordance and submission require the server-provided can_retry flag', async () => { const calls = [], safe = { id: 'safe', can_retry: true, kind: 'marketplace_reply' }, unsafe = { id: 'unsafe', can_retry: false, kind: 'password_recovery' }, h = ui(admin, async (url, options) => { if (options) calls.push({ url, body: plain(options.body) }); return options ? {} : overview({ recent: [safe, unsafe] }); }); await h.load(); h.selectRetry(unsafe); assert.equal(h.retryItem.value, null); h.selectRetry(safe); h.retryPassword.value = 'current'; await h.retry(); assert.deepEqual(calls, [{ url: '/api/admin/emails/retry', body: { id: 'safe', password: 'current' } }]); assert.equal(h.retryItem.value, null); });
test('suppression removal is an explicit separate operation with password and reason', async () => { let sent; const h = ui(admin, async (url, options) => { if (options) { sent = { url, body: plain(options.body) }; return { saved: true }; } return overview(); }); await h.load(); h.reviewSuppression({ email: 'recipient@example.test' }); assert.equal(h.suppression.suppressed, false); assert.equal(h.suppression.password, ''); h.suppression.password = 'current'; h.suppression.reason = 'Recipient confirmed repair'; await h.saveSuppression(); assert.deepEqual(sent, { url: '/api/admin/emails/suppressions', body: { email: 'recipient@example.test', reason: 'Recipient confirmed repair', suppressed: false, password: 'current' } }); });
test('central workspace replaces obsolete environment instructions and makes security preferences mandatory', () => { const recovery = read('app/pages/admin/passwords.vue'), page = read(personal), hub = read(admin); assert.match(recovery, /to="\/admin\/emails"/); assert.doesNotMatch(recovery, /RECOVERY_EMAIL_ENABLED|SMTP settings|server \.env|test-email/); assert.match(page, /mandatory/); assert.doesNotMatch(page, /v-model="[^"]*(?:security|password)/); assert.match(hub, /to="\/admin\/passwords"/); assert.match(hub, /autocomplete="off"/); assert.match(hub, /Record checks do not guarantee inbox delivery/); assert.doesNotMatch(hub, /<iframe|compliance certified|guaranteed delivery/i); });

test('email pages and entry points compile their actual Vue templates', () => { for (const file of [admin, personal, 'app/pages/admin/passwords.vue', 'app/pages/marketplace/inbox.vue', 'app/components/AppIcon.vue']) { const { descriptor, errors } = parse(read(file), { filename: file }); assert.deepEqual(errors, [], file); assert.doesNotThrow(() => compileScript(descriptor, { id: file, inlineTemplate: true }), file); } });
