import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { sellerAccess, parseAud, aud, canTransitionSale } from '../shared/marketplace.mjs';
import { CURRENT_FEATURES, PUBLIC_PAGES, safeReturnTo, testingAccess } from '../shared/platform.mjs';
import { PLAN_FEATURES } from '../shared/binder-types.mjs';
import { listingInput, listingEdit, messageInput, reportInput, queryInput, decodeSalePhoto, contentHash } from '../lib/marketplace-validation.mjs';
const payload = {request_id:randomUUID(),printing_id:randomUUID(),seller_alias:'Card collector',condition:'NM',price_minor:2499,delivery:'both',postage_minor:500,region:'Perth, WA',description:'A genuine card with minor wear; see the supplied photos.',ownership_confirmed:true,photos:[{},{}]};
const current={...payload,status:'active',hidden:false,revision:1};
const edit={revision:1,status:'reserved',price_minor:2499,postage_minor:500,description:payload.description};
test('listing has a fixed AUD ask without accepting inventory or payment fields',()=>{
 const parsed=listingInput(payload);assert.equal(parsed.price_minor,2499);assert.equal(parsed.ownership_confirmed,true);
 for(const key of ['seller_id','user_id','quantity','currency','status','hidden','subscription_status','payment_id'])assert.throws(()=>listingInput({...payload,[key]:'forged'}));
});
for(const [field,value] of [['price_minor',0],['price_minor',-1],['price_minor',12.9],['price_minor','2499'],['price_minor',10000001],['price_minor',NaN],['condition','MINT'],['postage_minor',-1],['delivery','courier-url'],['seller_alias',''],['description','tiny'],['region',''],['ownership_confirmed',false],['ownership_confirmed','true']]){
 test('listing rejects invalid '+field+' '+String(value),()=>assert.throws(()=>listingInput({...payload,[field]:value})));
}
test('front and back are required and pickup cannot carry a postage charge',()=>{assert.throws(()=>listingInput({...payload,photos:[]}));assert.throws(()=>listingInput({...payload,delivery:'pickup'}));assert.equal(listingInput({...payload,delivery:'pickup',postage_minor:0}).postage_minor,0)});
test('AUD amounts convert to exact integer cents without binary rounding',()=>{assert.equal(parseAud('12.34'),1234);assert.equal(parseAud('0.01'),1);assert.equal(parseAud('12.3'),1230);assert.equal(parseAud(' 12 '),1200);for(const value of ['-1','1e2','1,000','3.456','','Infinity',12,null])assert.equal(parseAud(value),null);assert.ok(aud(1234).includes('12.34'))});
test('seller transitions are explicit and sold is terminal',()=>{assert.equal(canTransitionSale('active','reserved'),true);assert.equal(canTransitionSale('reserved','sold'),true);assert.equal(canTransitionSale('withdrawn','active'),true);assert.equal(canTransitionSale('sold','active'),false);assert.equal(canTransitionSale('toString','active'),false);assert.equal(listingEdit(edit,current).status,'reserved')});
test('seller updates cannot change ownership, printing, photos or moderation',()=>{for(const key of ['seller_id','printing_id','photos','hidden'])assert.throws(()=>listingEdit({...edit,[key]:'forged'},current));assert.throws(()=>listingEdit({...edit,status:'active'},{...current,hidden:true}));assert.throws(()=>listingEdit({...edit,status:'active'},{...current,status:'sold'}));assert.throws(()=>listingEdit({...edit,status:'sold',price_minor:100},{...current,status:'sold'}))});
test('queries are bounded and use an explicit filter/sort vocabulary',()=>{assert.equal(queryInput().page,1);assert.equal(queryInput({mine:'true'}).mine,true);for(const q of [{page:0},{page:'1.1'},{order:'price_minor; drop table'},{condition:[]},{q:'a'.repeat(101)},{mine:'yes'}])assert.throws(()=>queryInput(q))});
test('messages require replay IDs and strict text, without sender impersonation',()=>{const r={request_id:randomUUID(),message:'Is this still available?'};assert.equal(messageInput(r).message,r.message);for(const bad of [{...r,message:''},{...r,message:'x'.repeat(2001)},{...r,sender_id:randomUUID()},{...r,request_id:'bad'}])assert.throws(()=>messageInput(bad));assert.throws(()=>messageInput(r,true));assert.equal(messageInput({...r,revision:2},true).revision,2)});
test('reports are private bounded text and cannot select their moderation result',()=>{assert.equal(reportInput({reason:'misleading',details:'The number appears different.'}).reason,'misleading');assert.throws(()=>reportInput({reason:'other',details:'short'}));assert.throws(()=>reportInput({reason:'other',details:'Please investigate this.',status:'resolved'}))});
test('sale photos reject forged MIME, SVG, excessive size and malformed encoding',()=>{
 const p={side:'front',content_type:'image/png',data_base64:Buffer.from('<svg/>').toString('base64')};assert.throws(()=>decodeSalePhoto(p));
 assert.throws(()=>decodeSalePhoto({...p,data_base64:'%%%%'}));assert.throws(()=>decodeSalePhoto({...p,data_base64:'A'.repeat(2666672)}));assert.throws(()=>decodeSalePhoto({...p,side:'extra'}));
 const jpeg={side:'back',content_type:'image/jpeg',data_base64:Buffer.from([255,216,255,0]).toString('base64')};assert.equal(decodeSalePhoto(jpeg).side,'back');assert.throws(()=>decodeSalePhoto({...jpeg,content_type:'image/png'}));
});
test('content identity detects changed asking prices and request data',()=>{assert.equal(contentHash(payload),contentHash({...payload}));assert.notEqual(contentHash(payload),contentHash({...payload,price_minor:2500}))});
test('selling belongs to Plus; browsing and enquiries belong to both plans',()=>{assert.ok(PLAN_FEATURES.collector.includes('marketplace_browse'));assert.ok(!PLAN_FEATURES.collector.includes('marketplace_sell'));assert.ok(PLAN_FEATURES.plus.includes('marketplace_sell'));assert.ok(PLAN_FEATURES.collector.every(f=>PLAN_FEATURES.plus.includes(f)))});
test('current non-enforced testing policy never introduces a seller paywall',()=>{assert.equal(sellerAccess({plan:'collector',status:'past_due'}).allowed,true);for(const grant of [{kind:'legacy_tester',expires_at:null},{kind:'beta_tester',expires_at:null},null]){const access=testingAccess(grant);assert.equal(access.payment_required,false);assert.equal(access.expires_at,null);assert.deepEqual(access.features,CURRENT_FEATURES);assert.ok(access.features.some(f=>f.code==='marketplace_sell'))}});
test('future seller policy still preserves tester grants and requires active Plus otherwise',()=>{assert.equal(sellerAccess({enforcement:true,plan:'collector',status:'active'}).allowed,false);assert.equal(sellerAccess({enforcement:true,plan:'plus',status:'past_due'}).allowed,false);assert.equal(sellerAccess({enforcement:true,plan:'plus',status:'active'}).allowed,true);assert.equal(sellerAccess({enforcement:true,grant:{kind:'legacy_tester',expires_at:null}}).allowed,true);assert.equal(sellerAccess({enforcement:true,grant:{kind:'beta_tester',expires_at:'2020-01-01'}}).allowed,false)});
test('marketplace deep links return after login but are not public marketing routes',()=>{for(const path of ['/marketplace','/marketplace/new','/marketplace/inbox?thread=abc'])assert.equal(safeReturnTo(path),path);assert.equal(safeReturnTo('/marketplace-evil'),'/app');assert.ok(!PUBLIC_PAGES.some(p=>p.startsWith('/marketplace')))});
test('marketplace migration does not mutate inventory, binders, grants or billing',()=>{const sql=readFileSync(new URL('../migrations/006_marketplace.sql',import.meta.url),'utf8');assert.doesNotMatch(sql,/(?:UPDATE|DELETE FROM|ALTER TABLE)\s+(?:collection_entries|binders|sessions|app_users|account_access_grants|account_memberships|membership_plans)\b/i);assert.match(sql,/UNIQUE\(seller_id, request_id\)/);assert.match(sql,/UNIQUE\(sender_id,request_id\)/)});
