import test from 'node:test';
import assert from 'node:assert/strict';
import {positiveAmount,extractPricing,quoteForPrinting,isStaleQuote,audConversion,displayPrice,valueRows} from '../lib/price-logic.mjs';
const now=Date.parse('2026-09-16T12:00:00Z'),date='2026-09-16T00:00:00.000Z';
const q={source:'TCGplayer',variant:'normal',currency:'USD',metric:'marketPrice',amount:10,source_updated_at:date};
const fx=[{currency:'USD',aud_rate:'1.5',rate_date:'2026-09-16'}];
const row={source:'tcgdex',key:'normal',quotes:[q],fetched_at:date,quantity:2};
test('only finite positive numeric market amounts are accepted',()=>{for(const value of [0,-1,NaN,Infinity,'10',null,undefined,10000001])assert.equal(positiveAmount(value),null);assert.equal(positiveAmount(0.01),0.01);});
test('extracts explicit TCGplayer printing market prices and source timestamps',()=>{const {quotes}=extractPricing({tcgplayer:{unit:'USD',updated:date,normal:{marketPrice:10},reverse:{marketPrice:15},holo:{marketPrice:20}}});assert.equal(quotes.length,3);assert.deepEqual(quotes[0],q);});
test('does not invent prices from low, mid or highest asking values',()=>assert.equal(extractPricing({tcgplayer:{unit:'USD',normal:{lowPrice:3,midPrice:5,highPrice:30}}}).quotes.length,0));
test('missing prices and unsupported currencies remain unpriced',()=>{assert.deepEqual(extractPricing(null),{quotes:[],references:[]});assert.equal(extractPricing({tcgplayer:{unit:'EUR',normal:{marketPrice:3}}}).quotes.length,0);});
test('Cardmarket references never become printing matches',()=>{const data=extractPricing({cardmarket:{unit:'EUR',updated:date,trend:4,'trend-holo':8}});assert.equal(data.references.length,2);assert.equal(data.quotes.length,0);assert.equal(quoteForPrinting(row,data.references),null);});
test('manual, first edition and unspecified printings never inherit normal prices',()=>{for(const key of ['manual-holo','firstEdition','shadowless','unspecified']) assert.equal(quoteForPrinting({source:'tcgdex',key},[q]),null);assert.equal(quoteForPrinting({source:'manual',key:'normal'},[q]),null);});
test('matching is exact across the supported finishes',()=>{assert.equal(quoteForPrinting(row,[q]),q);assert.equal(quoteForPrinting({...row,key:'reverse'},[q]),null);});
test('bad timestamps remain visible as unknown, not current',()=>{const data=extractPricing({tcgplayer:{unit:'USD',updated:'not a date',normal:{marketPrice:10}}});assert.equal(data.quotes[0].source_updated_at,null);assert.equal(isStaleQuote(data.quotes[0],date,now),true);});
test('stale source timestamps are not refreshed by a successful HTTP fetch',()=>assert.equal(isStaleQuote({...q,source_updated_at:'2026-09-01T00:00:00Z'},date,now),true));
test('stale fetches remain stale despite recent source data',()=>assert.equal(isStaleQuote(q,'2026-09-01T00:00:00Z',now),true));
test('future source dates do not qualify as current prices',()=>assert.equal(isStaleQuote({...q,source_updated_at:'2027-01-01T00:00:00Z'},date,now),true));
test('AUD conversion retains the actual source rate and date',()=>assert.deepEqual(audConversion(q,fx,now),{amount:15,currency:'AUD',rate:1.5,rate_date:'2026-09-16'}));
test('AUD conversion accepts a database Date object for the rate date',()=>assert.equal(audConversion(q,[{...fx[0],rate_date:new Date(date)}],now).amount,15));
test('missing, expired or invalid FX never defaults to a 1:1 rate',()=>{assert.equal(audConversion(q,[],now),null);for(const rate of [{...fx[0],aud_rate:'bad'},{...fx[0],aud_rate:-1},{...fx[0],rate_date:'2026-08-01'}])assert.equal(audConversion(q,[rate],now),null);});
test('display keeps original currency when AUD is unavailable',()=>{const p=displayPrice(q,{fetched_at:date},[],now);assert.equal(p.aud,null);assert.equal(p.amount,10);assert.equal(p.currency,'USD');});
test('collection totals multiply actual quantities and report coverage',()=>{const value=valueRows([row,{...row,key:'firstEdition',quantity:3}],fx,now);assert.equal(value.aud_total,30);assert.equal(value.quantity,5);assert.equal(value.priced_quantity,2);assert.equal(value.unpriced_quantity,3);});
test('stale and failed checks are excluded from headline totals',()=>{const value=valueRows([{...row,last_error:'Provider unavailable'},{...row,fetched_at:'2026-08-01'}],fx,now);assert.equal(value.aud_total,null);assert.equal(value.stale_quantity,4);});
test('an empty or wholly unpriced collection is not represented as worth zero',()=>{assert.equal(valueRows([],fx,now).aud_total,null);assert.equal(valueRows([{...row,quotes:[]}],fx,now).aud_total,null);});
test('FX missing has its own coverage count',()=>{const value=valueRows([row],[],now);assert.equal(value.aud_total,null);assert.equal(value.fx_missing_quantity,2);assert.equal(value.unpriced_quantity,0);});
test('zero quantities and malformed counts do not affect values',()=>{assert.equal(valueRows([{...row,quantity:0},{...row,quantity:-1}],fx,now).quantity,0);});
