<script setup lang="ts">
const api=useApi(),auth=useAuth(),data=ref<any>(null),error=ref(''),loading=ref(true)
async function load(){loading.value=true;error.value='';try{data.value=await api('/api/account/membership')}catch(e){error.value=errorMessage(e)}finally{loading.value=false}}
onMounted(load)
useSeoMeta({title:'Your account · CardShelf'})
</script>
<template>
<header class="page-heading"><div><span class="eyebrow">YOUR CARDSHELF ACCOUNT</span><h1>Your space. Your access.</h1><p>Your sign-in keeps you connected to your collection.</p></div><NuxtLink to="/" class="button secondary">Visit the website</NuxtLink></header>
<p v-if="error" class="alert error">{{error}}<button class="text-button" @click="load">Try again</button></p><p v-if="loading" class="loading-panel">Loading account details…</p>
<section v-if="data" class="panel settings-panel"><div class="section-heading"><div><h2>{{data.grant?'Protected access':'Account access'}}</h2><p>{{auth.state.value.user?.email}}</p></div><span class="badge" :class="{green:data.access.allowed}">{{data.access.allowed?(['stripe_subscription','legacy_paid_period'].includes(data.access.reason)?'Active membership':'Active · no payment required'):'Membership required'}}</span></div><p class="alert info">{{data.message}}</p><p v-if="data.grant" class="small muted">Your existing non-expiring testing grant is preserved. A paid subscription is not required.</p><div class="account-benefits"><p v-for="feature in data.access.features" :key="feature.code"><AppIcon name="check" :size="17" />{{feature.label}}</p></div><div class="button-row spaced"><NuxtLink to="/app" class="button primary">Open your collection</NuxtLink><NuxtLink to="/settings" class="button secondary">Password & data settings</NuxtLink></div></section>
<section class="panel settings-panel spaced"><h2>Sign-in security</h2><p class="small muted">Manage authenticator apps, passkeys, hardware security keys and one-time recovery codes.</p><p class="small muted">Email: {{ auth.state.value.user?.email_verified_at ? 'Verified' : auth.state.value.user?.email_verification_required ? 'Verification required' : 'Not verified · existing account access is preserved' }}</p><NuxtLink to="/security" class="button primary">Account security</NuxtLink></section>
<section class="panel settings-panel spaced"><h2>CardShelf on your device</h2><p class="small muted">Install the app and choose which updates arrive as push notifications.</p><NuxtLink to="/notifications" class="button secondary">App &amp; notifications</NuxtLink></section>
<section class="panel settings-panel spaced"><h2>Membership & referrals</h2><p class="small muted">Review your access, Stripe subscriptions and any referral programme you have been approved to join. Card sales are settled directly between collectors.</p><div class="button-row"><NuxtLink to="/membership" class="button secondary">Manage membership</NuxtLink><NuxtLink to="/referrals" class="button secondary">Your referrals</NuxtLink></div></section>
<section v-if="auth.state.value.user?.role==='admin'" class="panel settings-panel spaced"><h2>Platform administration</h2><p class="muted small">Manage people, complimentary access, subscription offers and approved referral rewards. Access changes and subscription billing are separate actions.</p><div class="button-row"><NuxtLink to="/admin/memberships" class="button primary">Memberships & referrals</NuxtLink><NuxtLink to="/admin" class="button secondary">Administration</NuxtLink></div></section>
</template>
