<script setup lang="ts">
definePageMeta({ layout: 'marketing' })
useMarketingSeo('Contact CardShelf', 'Get account or membership help, ask a question or contact CardShelf about your data.', '/contact')
const route = useRoute(), api = useApi(), busy = ref(false), sent = ref(false), error = ref('')
const initialPurpose = ['early_access','support','privacy'].includes(String(route.query.purpose)) ? String(route.query.purpose) : 'support'
const form = reactive({name:'',email:'',message:'',purpose:initialPurpose,consent:false,website:''})
async function submit() {
  if (busy.value) return
  busy.value=true;error.value=''
  try { await api('/api/public/access-requests',{method:'POST',body:{...form}});sent.value=true;form.name='';form.email='';form.message='' }
  catch (e) { error.value=errorMessage(e) } finally { busy.value=false }
}
</script>
<template><section class="m-container m-access-grid"><div class="m-access-copy"><span class="m-eyebrow">A LITTLE HELP FOR YOUR COLLECTION.</span><h1>Let’s get<br>you<br><em>sorted.</em></h1><p class="m-lead">Ask about your account, membership or collection. Your request goes to the CardShelf administrator.</p><div class="m-access-promises"><p><AppIcon name="check" />Account and membership help.</p><p><AppIcon name="check" />Support and privacy requests.</p><p><AppIcon name="check" />Existing accounts stay active.</p></div><p class="m-fine">Already have an account? <NuxtLink to="/login">Sign in here.</NuxtLink></p></div><div class="m-form-card"><template v-if="sent"><span class="m-success-icon"><AppIcon name="check" :size="30" /></span><span class="m-eyebrow">REQUEST RECORDED</span><h2>Your request is ready for review.</h2><p>Your request is saved for the administrator. It does not automatically create an account or send a confirmation email.</p><NuxtLink to="/" class="m-button">Back to CardShelf<AppIcon name="arrow" :size="17" /></NuxtLink><p class="m-fine">Existing members can continue signing in as usual.</p></template><template v-else><h2>Let’s make an introduction.</h2><p>For access, support or a question about your data.</p><form class="form-stack" @submit.prevent="submit"><label>Your name<input v-model="form.name" required maxlength="80" autocomplete="name" placeholder="Name" /></label><label>Email address<input v-model="form.email" type="email" required maxlength="254" autocomplete="email" placeholder="you@example.com" /></label><label>What brings you here?<select v-model="form.purpose"><option value="early_access">I need account or membership help</option><option value="support">I have a question</option><option value="privacy">I have a privacy or data request</option></select></label><label>A little more detail <span class="m-optional">(optional)</span><textarea v-model="form.message" maxlength="1200" rows="4" placeholder="What do you collect, or how can we help? Please don’t include passwords or payment information." /></label><div class="m-honeypot" aria-hidden="true"><label>Website<input v-model="form.website" tabindex="-1" autocomplete="off" /></label></div><label class="m-consent"><input v-model="form.consent" type="checkbox" required /><span>You may use these details to respond to this request. I’ve read the <NuxtLink to="/privacy">privacy & data information</NuxtLink>. This is not a newsletter signup.</span></label><p v-if="error" class="alert error" role="alert">{{ error }}</p><button class="m-button" :disabled="busy">{{ busy ? 'Sending request…' : 'Send my request' }}<AppIcon name="arrow" :size="18" /></button></form><p class="m-fine">Requests are reviewed manually. For a new account, see the Free account options.</p></template></div></section></template>
