<script setup lang="ts">
definePageMeta({ layout: 'marketing' })
useMarketingSeo('Made for the way you collect', 'Discover CardShelf’s collection tracking, custom binders, set and series layouts, market-price references, sharing, exports and the first-person Pokémon Arena.', '/features')
const features = [
  {id:'collection',number:'01',icon:'cards',title:'Know your collection. Right down to the printing.',description:'Keep quantities, conditions, notes and wishlists together. Search by card, set, illustrator or language, and switch between owned and missing views.',items:['Normal, Holo and Reverse Holo ownership records','Grid and list browsing with collection filters','English and Japanese catalogue imports','Clear labels where printing data is unspecified']},
  {id:'binders',number:'02',icon:'binder',title:'Make space for a complete set—or something entirely yours.',description:'Start blank, or create a binder from imported sets and series. Preview the layout before creating it, choose your pocket grid, and include missing cards or only the cards you own.',items:['Automatic page counts and numbered volumes','Collector-number ordering and optional new pages per set','Drag-to-swap on desktop and tap-to-move on mobile','No change to ownership when planning a pocket']},
  {id:'appearance',number:'03',icon:'star',title:'Your style. On every page.',description:'Give each binder its own colours or wallpaper. Adjust the image and pocket appearance, and distinguish known finishes with subtle decorative foil effects.',items:['Upload JPEG, PNG or WebP wallpaper','Opacity, blur, dimming and image-fit controls','Separate card-class badges and printing finishes','Optional backgrounds for printing']},
  {id:'pricing',number:'04',icon:'refresh',title:'Market context, without the mystery.',description:'Review provider-supplied market prices, AUD reference conversions and recorded observations. See what is priced, what is missing, and how fresh the data is.',items:['Background refresh for owned, wishlisted and planned cards','Source currencies, timestamps and exchange-rate dates','Collection and planned-binder value references','Unsupported or stale prices are not silently counted as zero']},
  {id:'arena',number:'05',icon:'cards',title:'A place to collect. A table to play.',description:'Step into the first-person Pokémon Arena: a walnut table, woven playmat, illustrated training decks and a private foreground hand. Learn with a coach, practise against the computer or invite another eligible member.',items:['Automatic turns, attacks and supported card effects','Deck building with clear card-support checks','Inspection, legal targets, match history and optional effects','Touch and keyboard controls, with a flat mobile layout']},
  {id:'sharing',number:'06',icon:'share',title:'Show the binder. Keep the private details.',description:'Create a read-only link when you want to share a binder’s planned layout and appearance. Your ownership quantities and private notes stay out of the shared view.',items:['Rotate or disable a sharing link','Download ownership JSON or CSV','Print missing-card placeholders and checklists','Keep account access separate from public sharing']}
]
</script>
<template><section class="m-container m-page-hero"><span class="m-eyebrow">THE CARDSHELF PLATFORM</span><h1>Everything in its place.<br><em>Nothing out of reach.</em></h1><p class="m-lead">Practical tools for the collection you’re building.<br>Thoughtful details for the hobby you love—from your first binder to your next match.</p><div class="m-actions"><NuxtLink to="/register" class="m-button">Get started<AppIcon name="arrow" :size="18" /></NuxtLink><NuxtLink to="/login" class="m-text-link">Already a member? Sign in</NuxtLink></div></section><section class="m-container m-feature-details"><article v-for="feature in features" :id="feature.id" :key="feature.id" class="m-detail-row"><div class="m-detail-marker"><span>{{ feature.number }}</span><AppIcon :name="feature.icon" :size="40" /></div><div><h2>{{ feature.title }}</h2><p>{{ feature.description }}</p><NuxtLink v-if="feature.id === 'arena'" to="/pokemon-arena" class="m-text-link">Discover the Arena<AppIcon name="arrow" :size="17" /></NuxtLink></div><ul><li v-for="item in feature.items" :key="item"><AppIcon name="check" :size="17" />{{ item }}</li></ul></article></section><section class="m-container m-feature-arena"><MarketingArenaPreview /><MarketingArenaAccess /></section><div class="m-container m-data-note"><AppIcon name="info" :size="22" /><p>Catalogue and pricing coverage depend on upstream data. A printing checklist is not a verified complete master-set catalogue. Market values are reference estimates, not appraisals or guaranteed sale prices. Use the card-support checks before entering an Arena match.</p></div><MarketingCta /></template>
