<script setup lang="ts">
definePageMeta({ layout: 'marketing' })
useMarketingSeo('Collect, organise and play', 'Track your cards, build beautiful digital binders and take your seat in CardShelf Arena. Discover guided Pokémon training, computer practice and private matches.')
const questions = [
  {q:'What can I do with CardShelf today?',a:'Track ownership by printing and condition, create custom binders, generate layouts from imported sets or series, customise wallpapers, view market-price references, share read-only binders and export your collection records. Eligible members can also learn, practise and play private Pokémon matches in Arena.'},
  {q:'How can I start using CardShelf?',a:'Browse the catalogue for free, then create a Free account when registration is open. Private collecting tools and Arena depend on your membership; see Plans & access. Existing invited testers retain their non-expiring collecting access.'},
  {q:'What is the new CardShelf Arena?',a:'A first-person Pokémon tabletop with guided training, computer practice and private matches. The game resolves supported attacks and effects while you choose your moves. Arena requires Collector, Collector Plus or an explicitly assigned Complimentary account, and must be enabled on the site.'},
  {q:'Are market prices live?',a:'Prices refresh in the background for tracked cards. They depend on the source provider and are not a second-by-second feed. CardShelf shows timestamps, pricing coverage and AUD reference conversions. Estimates are not condition-specific appraisals.'},
  {q:'Is my collection visible to everyone?',a:'No. Your collection and workspace require sign-in. You choose whether to enable a read-only binder link. That link shares its planned layout and appearance, not your private quantities or notes, and you can revoke it.'},
  {q:'Can I take my collection records with me?',a:'Yes. Download your ownership records as JSON or CSV. Printable binder placeholders and checklists are also included. A collection export is not a complete server backup.'}
]
</script>
<template>
  <section class="m-container m-hero">
    <div class="m-hero-copy"><NuxtLink to="/pokemon-arena" class="m-announcement"><span class="m-live-dot" />NEW LOOK. YOUR SEAT AT THE TABLE.<AppIcon name="arrow" :size="14" /></NuxtLink><h1>Every card.<br>Every match.<br><em>One beautiful home.</em></h1><p class="m-lead">Track what you own. Build binders you love. Then pull up a chair in Arena for guided training, computer practice and private Pokémon matches.</p><div class="m-actions"><NuxtLink to="/register" class="m-button">Get started<AppIcon name="arrow" :size="18" /></NuxtLink><NuxtLink to="/pokemon-arena" class="m-button m-button-quiet">Discover Arena</NuxtLink></div><p class="m-fine"><AppIcon name="check" :size="15" />Free catalogue browsing. Membership options for collecting and Arena.</p></div>
    <MarketingDemo />
  </section>
  <div class="m-proof-band"><div class="m-container"><span><AppIcon name="cards" />English & Japanese catalogue</span><span><AppIcon name="grid" />Printing-aware collecting</span><span><AppIcon name="binder" />Binders made yours</span><span><AppIcon name="cards" />A new way to play</span></div></div>
  <section class="m-arena-showcase" aria-labelledby="home-arena-heading"><div class="m-container"><div class="m-arena-showcase-heading"><div><span class="m-eyebrow">MEET THE NEW CARDSHELF ARENA</span><h2 id="home-arena-heading">From the binder<br><em>to the table.</em></h2></div><div><p>A warm room. A beautifully textured table. Your next move, right in front of you. Discover a first-person Pokémon Arena built for learning, practising and playing together.</p><NuxtLink to="/pokemon-arena" class="m-button">Explore the Arena<AppIcon name="arrow" :size="18" /></NuxtLink></div></div><MarketingArenaPreview /><div class="m-arena-highlights"><span><AppIcon name="cards" :size="19" />Guided training</span><span><AppIcon name="refresh" :size="19" />Computer practice</span><span><AppIcon name="share" :size="19" />Private matches</span><span><AppIcon name="check" :size="19" />Automatic supported rules</span></div></div></section>
  <section class="m-container m-section" id="platform"><div class="m-section-heading"><span class="m-eyebrow">LESS SPREADSHEET. MORE COLLECTION.</span><h2>A place for the cards you have.<br>And the ones you’re still chasing.</h2><p>Bring the practical side of collecting together, without losing what makes the hobby yours.</p></div>
    <div class="m-bento">
      <article class="m-feature-card m-feature-large"><span class="m-feature-number">01 / BUILD</span><h3>From an entire series<br>to your personal favourites.</h3><p>Start with a blank binder or generate a layout from your imported sets. Choose your pocket grid, leave space for missing cards, and make every page your own.</p><NuxtLink to="/features#binders" class="m-text-link">Explore binder planning<AppIcon name="arrow" :size="17" /></NuxtLink><div class="m-mini-binders" aria-hidden="true"><div><AppIcon name="binder" :size="32" /><span>THE<br>MASTER SET.</span><small>SET BY SET</small></div><div><AppIcon name="star" :size="32" /><span>PERSONAL<br>FAVOURITES.</span><small>MADE YOURS</small></div><div><AppIcon name="cards" :size="32" /><span>THE NEXT<br>GREAT FIND.</span><small>ROOM TO GROW</small></div></div></article>
      <article class="m-feature-card m-feature-collection"><span class="m-feature-icon"><AppIcon name="cards" :size="25" /></span><h3>The details matter.</h3><p>Track quantities, conditions and wishlists by printing. Keep Normal, Holo and Reverse Holo records distinct.</p><div class="m-finish-list"><span>Normal<i /></span><span>Holo<i /></span><span>Reverse Holo<i /></span></div></article>
      <article class="m-feature-card m-feature-price"><span class="m-feature-icon"><AppIcon name="refresh" :size="25" /></span><h3>A clearer view of value.</h3><p>Market-price references, AUD estimates and recorded history—with sources, timestamps and missing-price coverage shown.</p><div class="m-price-pills"><span>Source-linked</span><span>AUD references</span><span>No guessed prices</span></div></article>
      <article class="m-feature-card m-feature-wide"><div><span class="m-feature-number">04 / MAKE IT YOURS</span><h3>A binder with your personality.</h3><p>Custom wallpaper. Your colour palette. Subtle foil effects. A collection that feels like yours, right down to the pockets.</p></div><div class="m-style-samples" aria-hidden="true"><span /><span /><span /><span /></div></article>
    </div>
  </section>
  <section class="m-workflow"><div class="m-container"><div class="m-section-heading"><span class="m-eyebrow">A BETTER COLLECTING ROUTINE</span><h2>Organised in three satisfying steps.</h2></div><div class="m-three-up"><article><span class="m-step">01</span><h3>Bring your sets together.</h3><p>Browse the imported catalogue and record the printings you own. Add your wishlist along the way.</p></article><article><span class="m-step">02</span><h3>Build your perfect binder.</h3><p>Generate a set layout or create something personal. Move, swap and style your cards, page by page.</p></article><article><span class="m-step">03</span><h3>Enjoy the bigger picture.</h3><p>See your progress and market-price references. Share a read-only binder or export your records.</p></article></div></div></section>
  <section class="m-container m-story"><div><span class="m-eyebrow">COLLECTING IS PERSONAL</span><h2>Not just what it’s worth.<br><em>What it means to you.</em></h2><p>The first set you finished. A favourite illustrator. That one empty pocket you’re determined to fill. CardShelf gives those collections a place to take shape.</p><NuxtLink to="/features" class="m-text-link">See what’s inside<AppIcon name="arrow" :size="18" /></NuxtLink></div><div class="m-story-panel"><AppIcon name="binder" :size="42" /><blockquote>Keep the collection.<br>Lose the guesswork.</blockquote><span>BUILT AROUND YOUR WAY OF COLLECTING</span><div class="m-story-links"><span><AppIcon name="shield" :size="17" />Private by default</span><span><AppIcon name="share" :size="17" />Shared by choice</span></div></div></section>
  <section id="questions" class="m-container m-faq-section"><div><span class="m-eyebrow">A FEW THINGS WORTH KNOWING</span><h2>Good questions.<br>Straight answers.</h2><p>Something else on your mind?</p><NuxtLink to="/contact?purpose=support" class="m-text-link">Send a question<AppIcon name="arrow" :size="16" /></NuxtLink></div><div class="m-faq"><details v-for="item in questions" :key="item.q"><summary>{{ item.q }}<AppIcon name="plus" :size="18" /></summary><p>{{ item.a }}</p></details></div></section>
  <MarketingCta />
</template>
