<script setup lang="ts">
definePageMeta({ layout: 'marketing' })
useMarketingSeo('Privacy & data', 'How CardShelf handles accounts, collection records, marketplace messages, optional Stripe subscriptions and approved referrals.', '/privacy')
</script>
<template><section class="m-container m-page-hero m-privacy-hero"><span class="m-eyebrow">PRIVACY & DATA</span><h1>Your collection.<br><em>Clear boundaries.</em></h1><p class="m-lead">How CardShelf handles your account, collection and service data.</p></section><article class="m-container m-prose">
<h2>Accounts and collections</h2><p>The service stores your name, email address, password hash, sign-in sessions and the collection records you choose to add. Private collection and binder actions require a signed-in account. The server operator administers the database, backups and user accounts.</p>
<h2>Testing, complimentary access and subscriptions</h2><p>Existing tester grants remain non-expiring. Administrators can separately assign tiers or complimentary access. These audited access changes do not create or cancel a subscription, and complimentary access does not grant administrator permissions.</p><p>When you explicitly request a paid subscription, CardShelf sends your account name, email and an account reference to Stripe. Stripe hosts checkout and billing management and handles recurring payments. CardShelf stores provider references, accepted terms, payment status, dates and verified payment history; it does not collect full card numbers or card security codes. Sandbox customer details are synthetic.</p><p>Administrators control new subscription availability and feature enforcement separately. Stopping new subscriptions does not cancel existing renewals. Historical records from a retired payment provider remain read-only for accounting and previously verified access; no new payment requests are sent to that provider.</p>
<h2>Referral programme</h2><p>Referral participation requires administrator approval and your explicit acceptance of the reward terms. An attributed subscriber confirms use of a referral code before subscribing. The service records the attribution, accepted terms, eligible subscription commissions, refunds and manually recorded external payout references. Referrers can see their own totals and ledger, not subscriber identities or payment details. Administrators can see and manage these records. Referral links do not set an advertising cookie; attribution is recorded only when the signed-in subscriber confirms it.</p>
<h2>Marketplace</h2><p>Card listings deliberately share the seller alias, selected card, photographs, description, price and delivery details with signed-in members. Listing enquiries are visible to the participants through the application. Card-sale payments and delivery arrangements remain between collectors; CardShelf does not process them. The database operator has administrative access to stored data and backups.</p>
<h2>Account emails and notifications</h2><p>When email delivery is enabled, CardShelf uses the operator's selected Postal or external SMTP mail service (such as WPMU DEV) for password recovery and account security notices. Optional marketplace and membership notifications are controlled under More → Emails. Activity emails link you back to CardShelf without including private conversation text. The mail service processes your email address and the message contents, including a temporary recovery link when you request one. Administrators can inspect delivery status and manage addresses that cannot receive mail. Delivery records and suppression records support retries and prevent repeated sending to failed addresses. External SMTP providers process mail under their own retention and data policies; the operator chooses that service and manages Postal retention and backups when Postal is used.</p>
<h2>Access, support and privacy requests</h2><p>The request form stores the name, email address, request type and message you submit, with its consent version and review status. Only platform administrators can view the queue. Submitting it does not create an account or subscribe you to a mailing list. Administrators remove requests when no longer required.</p>
<h2>Cookies and technical records</h2><p>CardShelf uses a first-party sign-in cookie and server-side sessions. Rate-limit records, logs and audit events support operation. Stripe webhook processing retains verified routing identifiers and status, not entire raw webhook payloads. The selected advertising provider may load third-party scripts, identifiers and cookies on eligible content pages. See the advertising information below for provider scope and exclusions.</p>
<h2>Images and sharing</h2><p>Wallpaper and sale-photo uploads are decoded, optimised and re-encoded before storage. Original filenames and image metadata are not retained by those flows. A binder wallpaper is accessible to its owner and, when enabled, through its read-only sharing link. Shared trackers expose their checklist marks. Revoking a link cannot recall screenshots or copies already made.</p>
<h2>Catalogue and price providers</h2><p>Pokémon catalogue and market-price requests use TCGdex, with artwork fallbacks from Pokémon and Limitless TCG. Additional games use YGOPRODeck and MTGJSON, with Magic artwork from Scryfall. Some artwork is rehosted locally; external image hosts receive the connection information needed to serve requested images. Currency reference requests use Frankfurter. Full collection databases, private notes and passwords are not sent to these providers.</p>
<h2>Card photo recognition</h2><p>When you choose to analyse a card photo, CardShelf sends the prepared image to OpenAI for recognition. Review the match before adding anything to your collection. CardShelf does not retain the uploaded photo; recognition results and usage records support review, retries and service accounting. The external recognition service handles the image under its API data policies.</p>
<h2>Device push notifications</h2><p>Enabling push on a device stores its subscription endpoint, encryption keys, preferences and a reference to your current sign-in session. CardShelf sends encrypted notifications through the browser or device push service. Notifications contain a general activity notice and a CardShelf link, without private message text. Device push and email preferences are separate. Signing out disables push for that sign-in.</p>
<h2>Exports and data requests</h2><p>Ownership exports contain JSON or CSV records, not every account or database record. The administrator manages broader data requests and retention, including billing, referral, marketplace and backup records. No automated retention schedule for those records is included. Use the contact form for help with your data. Do not include a password or payment-card information.</p><NuxtLink to="/contact?purpose=privacy" class="m-button">Send a data request<AppIcon name="arrow" :size="18" /></NuxtLink><p class="m-fine">The service operator maintains hosting, retention, service terms and subscription/referral disclosures. Use the contact form for questions about these arrangements.</p>
</article><FreePrivacyNotice /></template>
