<script setup lang="ts">
definePageMeta({ layout: 'marketing' })
useMarketingSeo('Privacy & data', 'How CardShelf handles accounts, collection records, marketplace messages, optional Square subscriptions and approved referrals.', '/privacy')
</script>
<template><section class="m-container m-page-hero m-privacy-hero"><span class="m-eyebrow">PRIVACY & DATA</span><h1>Your collection.<br><em>Clear boundaries.</em></h1><p class="m-lead">A practical description of how this beta handles data.</p></section><article class="m-container m-prose">
<h2>Accounts and collections</h2><p>The service stores your name, email address, password hash, sign-in sessions and the collection records you choose to add. Private collection and binder actions require a signed-in account. The server operator administers the database, backups and user accounts.</p>
<h2>Testing, complimentary access and subscriptions</h2><p>Existing tester grants remain non-expiring. Administrators can separately assign account tiers or complimentary access; these changes are audited and do not automatically create or cancel a paid subscription. Complimentary access does not grant administrator permissions.</p><p>Subscription billing is optional and disabled on upgrade. When enabled and you explicitly request a production subscription, CardShelf sends your account name, email and an account reference to Square, which issues recurring invoices and hosts the payment page. CardShelf stores provider identifiers, selected terms, invoice/payment status, amounts, dates and verified payment history. It does not collect your card number, card security code or bank account details. Sandbox tests use synthetic customer details rather than your real profile.</p>
<h2>Referral programme</h2><p>Referral participation requires administrator approval and your explicit acceptance of the reward terms. An attributed subscriber confirms use of a referral code before subscribing. The service records the attribution, accepted terms, eligible subscription commissions, refunds and manually recorded external payout references. Referrers can see their own totals and ledger, not subscriber identities or payment details. Administrators can see and manage these records. Referral links do not set an advertising cookie; attribution is recorded only when the signed-in subscriber confirms it.</p>
<h2>Marketplace</h2><p>Card listings deliberately share the seller alias, selected card, photographs, description, price and delivery details with signed-in members. Listing enquiries are visible to the participants through the application. Card-sale payments and delivery arrangements remain between collectors; CardShelf does not process them. The database operator has administrative access to stored data and backups.</p>
<h2>Access, support and privacy requests</h2><p>The request form stores the name, email address, request type and message you submit, with its consent version and review status. Only platform administrators can view the queue. Submitting it does not create an account or subscribe you to a mailing list. Administrators remove requests when no longer required.</p>
<h2>Cookies and technical records</h2><p>CardShelf uses a first-party sign-in cookie and server-side sessions. Rate-limit records, logs and audit events support operation. Square webhook processing retains verified routing identifiers and status, not entire raw webhook payloads. This release does not add advertising trackers or third-party analytics cookies.</p>
<h2>Images and sharing</h2><p>Wallpaper and sale-photo uploads are decoded, optimised and re-encoded before storage. Original filenames and image metadata are not retained by those flows. A binder wallpaper is accessible to its owner and, when enabled, through its read-only sharing link. Shared trackers expose their checklist marks. Revoking a link cannot recall screenshots or copies already made.</p>
<h2>Catalogue and price providers</h2><p>Catalogue and market-price requests use TCGdex. Card artwork loads from its image host, which receives ordinary connection information needed to serve images. Currency reference requests use Frankfurter. Full collection databases, private notes and passwords are not sent to these providers.</p>
<h2>Stripe subscription payments</h2><p>When a subscription-ready member explicitly chooses Stripe, CardShelf creates an account-bound hosted checkout. Production customer names and email addresses are sent to Stripe for billing; test mode uses synthetic details. Payment-card entry and saved payment methods remain with Stripe. CardShelf stores provider identifiers, accepted terms, invoice totals, verified paid periods and refund/dispute status, not full card numbers. Administrator credentials are encrypted using the server integration key. Referral rewards use verified production subscription payments and do not disclose subscriber contact details to referrers. Marketplace payments and referral payouts remain external.</p><h2>Exports and data requests</h2><p>Ownership exports contain JSON or CSV records, not every account or database record. The administrator manages broader data requests and retention, including billing, referral, marketplace and backup records. No automated retention schedule for those records is included. Contact the operator who invited you or use this form. Do not include a password or payment-card information.</p><NuxtLink to="/early-access?purpose=privacy" class="m-button">Send a data request<AppIcon name="arrow" :size="18" /></NuxtLink><p class="m-fine">This describes the implemented beta. The operator must review hosting, retention, service terms, subscription/referral disclosures and its wider obligations before a paid public launch.</p>
</article></template>
