<script setup lang="ts">
const api=useApi(),state=ref<any>(null),error=ref(''),notice=ref(''),busy=ref(false),consent=ref(false),origin=ref('')
const money=(n:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(n/100)
const link=computed(()=>state.value?.active?`${origin.value}/membership?ref=${state.value.partner.code}`:'')
const reward=computed(()=>state.value?.partner?.reward_type==='percentage'?`${(state.value.partner.reward_value/100).toFixed(2)}% of eligible subscription revenue`:money(state.value?.partner?.reward_value??0)+' per eligible billing cycle')
const label=(r:any)=>r.blocked?'On hold':r.earned_minor<r.paid_minor?'Refund adjustment — administrator review':r.earned_minor===r.paid_minor?(r.paid_minor?'Recorded paid':'Reversed'):new Date(r.eligible_at)>new Date()?'Holding period':r.approved?'Approved for manual payment':'Awaiting administrator review'
async function load(){try{state.value=await api('/api/referrals/account')}catch(e){error.value=errorMessage(e)}}
async function opt(value:boolean){busy.value=true;error.value='';try{await api('/api/referrals/consent',{method:'POST',body:{revision:state.value.partner.revision,consent:value}});consent.value=false;await load();notice.value=value?'You are opted in. Your referral link is ready.':'You have opted out. Previously recorded earnings have not been deleted.'}catch(e){error.value=errorMessage(e)}finally{busy.value=false}}
async function copy(){try{await navigator.clipboard.writeText(link.value);notice.value='Referral link copied.'}catch{notice.value='Select and copy the link below.'}}
onMounted(()=>{origin.value=window.location.origin;load()})
useSeoMeta({title:'Referral programme · CardShelf'})
</script>
<template><main class="membership-page"><header class="page-heading"><div><span class="eyebrow">INVITE COLLECTORS</span><h1>Share CardShelf. Earn transparently.</h1><p>An invitation-only referral programme with terms set by the administrator.</p></div><NuxtLink to="/membership" class="button secondary">Membership</NuxtLink></header>
<p v-if="error" class="alert error" role="alert">{{error}}</p><p v-if="notice" class="alert info" role="status">{{notice}}</p>
<section v-if="state&&!state.partner" class="panel settings-panel"><h2>Participation is by approval</h2><p>The administrator must approve your account and set your referral terms before you can opt in. An ordinary account or complimentary tier does not automatically enrol you.</p><NuxtLink to="/early-access" class="button secondary">Contact the administrator</NuxtLink></section>
<section v-if="state?.partner" class="panel settings-panel"><div class="section-heading"><h2>{{state.active?'Your referral programme is active':'Review your referral terms'}}</h2><span class="badge">{{state.partner.status==='suspended'?'Suspended':state.active?'Approved & opted in':'Opt-in required'}}</span></div>
<p><strong>{{reward}}</strong></p><p>Applies to the first {{state.partner.max_payments}} billing cycle(s) of each referred account’s first production subscription, after a {{state.partner.hold_days}}-day hold. Taxes and refunds are excluded or adjusted. Stripe processing fees are not deducted from the calculation. No sandbox payments, complimentary access or card sales earn commission.</p>
<pre class="membership-terms">{{state.partner.terms}}</pre>
<template v-if="state.active"><label>Your referral link<input :value="link" readonly @focus="($event.target as HTMLInputElement).select()"></label><div class="button-row spaced"><button class="button primary" @click="copy">Copy referral link</button><button class="button secondary" :disabled="busy" @click="opt(false)">Opt out</button></div><p class="small muted">The new subscriber must claim the code before their first production subscription request. It never assigns a plan, takes a payment or changes their access. Share the referral relationship clearly.</p></template>
<form v-else-if="state.partner.status==='approved'" @submit.prevent="opt(true)"><label class="membership-check"><input v-model="consent" type="checkbox" required>I accept these referral terms and agree to disclose the referral relationship when sharing my link.</label><button class="button primary" :disabled="!consent||busy">Opt in to these terms</button></form>
<p v-else class="alert info">The administrator has suspended new participation. Recorded earnings remain visible below.</p>
</section>
<section v-if="state" class="panel settings-panel spaced"><h2>Your referral ledger</h2><p>{{state.referred_accounts}} account(s) have claimed your referral. Earnings require verified subscription payments, not clicks or sign-ups.</p><p class="small muted">Payments are arranged by the administrator outside CardShelf. “Recorded paid” is an administrative record, not a transfer made by this website. Subscriber identities are not disclosed here.</p>
<div class="membership-table"><table><thead><tr><th>Reference</th><th>Earned</th><th>Recorded paid</th><th>Status</th></tr></thead><tbody><tr v-for="r in state.earnings" :key="r.id"><td>{{r.id.slice(0,8)}}</td><td>{{money(r.earned_minor)}}</td><td>{{money(r.paid_minor)}}</td><td>{{label(r)}}</td></tr></tbody></table></div><p v-if="!state.earnings.length" class="muted">No commission entries yet.</p><p class="small muted">Showing the latest 100 entries.</p>
</section></main></template>
<style src="~/assets/css/membership.css"></style>
