<script setup lang="ts">
const api=useApi(),auth=useAuth(),environment=ref('sandbox'),data=ref<any>(null),prices=ref<any[]>([]),cursor=ref<string|null>(null)
const busy=ref(false),error=ref(''),notice=ref('')
const setup=reactive({secret_key:'',webhook_secret:'',portal_id:'',password:'',accepting_new:false,confirm:false})
const offer=reactive({price_id:'',plan_code:'collector',tax_rate_id:'',terms:''})
const money=(n:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(n/100)
const date=(s:any)=>s?new Date(s).toLocaleString('en-AU'):'Not yet'
const path=(action:string)=>'/api/admin/integrations/stripe/'+action+'?environment='+environment.value
async function load(){try{data.value=await api(path('status'));setup.portal_id=data.value.portal_id;setup.accepting_new=data.value.accepting_new}catch(e){error.value=errorMessage(e)}}
async function run(task:()=>Promise<unknown>,message='Saved.'){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await task();notice.value=message;await load()}catch(e){error.value=errorMessage(e)}finally{busy.value=false;setup.password=''}}
async function save(){await run(async()=>{await api(path('settings'),{method:'POST',body:{...setup,revision:data.value.revision}});setup.secret_key='';setup.webhook_secret='';setup.confirm=false},'Stripe credentials verified and stored securely. Subscription activation and existing access were not changed.')}
async function loadPrices(more=false){await run(async()=>{const r=await api<any>(path('prices')+(more&&cursor.value?'&cursor='+encodeURIComponent(cursor.value):''));prices.value=more?[...prices.value,...r.prices]:r.prices;cursor.value=r.next_cursor},'Compatible recurring AUD prices loaded.')}
async function saveOffer(){await run(async()=>{await api(path('offers'),{method:'POST',body:{...offer}});offer.price_id='';offer.tax_rate_id='';offer.terms=''},'Unpublished Stripe offer saved. Verify and publish when ready.')}
async function publish(o:any){if(!o.published&&!window.confirm('Publish this Stripe offer after reviewing its recurring amount, configured tax and terms? This does not enable subscriptions; use Subscription controls above.'))return;await run(()=>api(path('offers/'+o.id),{method:'POST',body:{revision:o.revision,published:!o.published,confirm_terms_reviewed:true}}),o.published?'Offer paused; existing subscriptions continue.':'Offer published.')}
async function deleteOffer(o:any){
  if(busy.value||!o.can_delete)return
  const tier=o.plan_code==='plus'?'Collector Plus':'Collector',cadence=o.cadence==='MONTHLY'?'month':'year'
  if(!window.confirm(`Delete the draft ${tier} offer for ${money(o.total_minor)} / ${cadence} (${o.price_id})? You can add this Stripe price again with the correct tier.`))return
  await run(()=>api(path('offers/'+o.id+'/delete'),{method:'POST',body:{revision:o.revision,confirm:true}}),'Draft offer deleted. You can now add its Stripe price with the correct tier.')
}
async function cancel(s:any){if(!window.confirm('Cancel future renewals or expire the uncompleted checkout for '+s.email+'? This is not a refund and does not remove tester access.'))return;await run(()=>api(path('subscriptions/'+s.id+'/cancel'),{method:'POST',body:{confirm:true}}),'Cancellation requested. Review the refreshed status.')}
watch(environment,()=>{data.value=null;prices.value=[];cursor.value=null;error.value='';notice.value='';Object.assign(setup,{secret_key:'',webhook_secret:'',password:'',portal_id:'',accepting_new:false,confirm:false});load()})
onMounted(load)
useSeoMeta({title:'Stripe integration · CardShelf',robots:'noindex, nofollow'})
</script>
<template><main class="membership-page stripe-admin">
<header class="page-heading"><div><span class="eyebrow">PAYMENT INTEGRATIONS</span><h1>Stripe, connected.</h1><p>Secure subscription checkout. Your community’s access stays under your control.</p></div><div class="button-row"><NuxtLink to="/admin/memberships" class="button secondary">Memberships & referrals</NuxtLink></div></header>
<p v-if="auth.state.value.user?.role!=='admin'" class="alert error">Administrator access is required.</p>
<p v-if="error" class="alert error" role="alert">{{error}}</p><p v-if="notice" class="alert info" role="status">{{notice}}</p>
<StripeBillingControls v-if="auth.state.value.user?.role==='admin'" @saved="load" />
<section class="panel settings-panel"><div class="section-heading"><div><h2>Connection workspace</h2><p class="small muted">Test and Live credentials are separate. Switching this credential workspace does not change the active mode. Use Subscription controls above to activate a mode.</p></div><label>Environment<select v-model="environment" :disabled="busy"><option value="sandbox">Test / Sandbox</option><option value="production">Live / Production</option></select></label></div>
<template v-if="data"><div class="membership-status-grid"><div><small>Connected business</small><strong>{{data.account_name||'Not connected'}}</strong><code>{{data.account_id}}</code></div><div><small>Active subscription mode</small><strong>{{data.active_environment==='production'?'Live':'Test'}}</strong></div><div><small>New checkout switch</small><strong>{{data.billing_switch&&data.accepting_new?'Enabled':'Disabled / paused'}}</strong></div><div><small>Access enforcement</small><strong>{{data.enforcement_switch?'Enabled':'Off — testing access'}}</strong></div></div><p class="small muted">Last connection check: {{date(data.checked_at)}} · Last signed webhook: {{date(data.webhook_seen_at)}}</p><p v-if="data.last_error" class="alert error">{{data.last_error}}</p>
<p class="alert info">This connection is for CardShelf subscriptions only. No marketplace checkout, seller payouts or referral money transfers are initiated. Connecting does not charge existing testers or complimentary members.</p>
<p v-if="!data.key_available" class="alert error">The server encryption key is missing. Run <code>sudo sh scripts/configure-integrations.sh</code> and restart the application before saving credentials. Never post this key here or replace a working key.</p>
<form class="membership-form" @submit.prevent="save"><div class="stripe-two"><label>{{data.configured?'Replace secret key (leave blank to retain)':'Stripe secret key'}}<input v-model="setup.secret_key" type="password" autocomplete="new-password" maxlength="300" :placeholder="environment==='sandbox'?'sk_test_… or rk_test_…':'sk_live_… or rk_live_…'"></label><label>{{data.configured?'Replace webhook secret (leave blank to retain)':'Webhook signing secret'}}<input v-model="setup.webhook_secret" type="password" autocomplete="new-password" maxlength="300" placeholder="whsec_…"></label></div><label>Customer portal configuration ID<input v-model="setup.portal_id" maxlength="250" placeholder="bpc_…"></label><p class="small muted">Configure the portal in Stripe: enable payment-method updates, invoice history and cancellation at period end. Leave subscription plan changes disabled. No publishable key is needed for hosted Checkout.</p><label class="membership-check"><input v-model="setup.accepting_new" type="checkbox"><span>Allow offers for this connection. Subscription controls above enable the active mode. Unchecking pauses new requests, not existing renewals or checkout links.</span></label><label>Confirm your administrator password<input v-model="setup.password" type="password" required autocomplete="current-password"></label><label class="membership-check"><input v-model="setup.confirm" type="checkbox" required><span>I understand this connection manages CardShelf subscriptions only, and saving credentials does not enable subscriptions or charge existing users.</span></label><div class="button-row"><button class="button primary" :disabled="busy||!data.key_available">Verify & save connection</button><button type="button" class="button secondary" :disabled="busy||!data.configured" @click="run(()=>api(path('test'),{method:'POST',body:{}}),'Connection verified without creating a charge.')">Test connection</button></div></form>
<details class="spaced"><summary>Webhook and initial setup</summary><p>Create a Stripe account webhook destination using snapshot events and API version <code>2025-06-30.basil</code>. Copy its signing secret into the protected form above. Do not select connected-account events.</p><label>Webhook endpoint<input :value="data.webhook_url" readonly @focus="($event.target as HTMLInputElement).select()"></label><p class="small muted">Events: checkout.session.completed, checkout.session.expired, customer.subscription.created / updated / deleted, invoice.paid / payment_failed / updated, charge.refunded, charge.dispute.created / updated / closed, refund.created / updated.</p><p class="small muted">Use Subscription controls above to enable Test subscriptions, choose Live mode and manage enforcement without editing .env. Keep enforcement off during evaluation. Test the complete flow in <code>docs/STRIPE.md</code> before Live activation.</p></details></template></section>
<section v-if="data" class="panel settings-panel spaced"><div class="section-heading"><div><h2>Plans, not payment code.</h2><p class="small muted">Map your Stripe recurring prices to Collector or Collector Plus.</p></div><button class="button secondary" :disabled="busy||!data.configured" @click="loadPrices()">Load Stripe prices</button></div><form class="membership-form" @submit.prevent="saveOffer"><label>Stripe recurring price<select v-model="offer.price_id" required><option value="">Choose an imported Stripe price</option><option v-for="p in prices" :key="p.price_id" :value="p.price_id">{{p.name}} — {{money(p.amount_minor)}} / {{p.cadence==='MONTHLY'?'month':'year'}}</option></select></label><button v-if="cursor" type="button" class="text-button" :disabled="busy" @click="loadPrices(true)">Load more prices</button><div class="stripe-two"><label>CardShelf tier<select v-model="offer.plan_code"><option value="collector">Collector</option><option value="plus">Collector Plus</option></select></label><label>Optional fixed Stripe tax rate ID<input v-model="offer.tax_rate_id" placeholder="txr_… or leave blank" maxlength="250"></label></div><p class="small muted">With no tax rate, no tax is added by this integration. A fixed rate can be inclusive or exclusive; verify the resulting total before publishing. Automatic Tax, promotions, trials, metered prices and prorated changes are not supported here.</p><label>Recurring subscription terms<textarea v-model="offer.terms" required minlength="60" maxlength="6000" rows="5" placeholder="Price and cadence, renewal consent, cancellation and refund information, and operator contact details."></textarea></label><button class="button primary" :disabled="busy||!offer.price_id">Save draft offer</button></form><div class="membership-table-wrap spaced"><table><thead><tr><th>Tier</th><th>Total / cadence</th><th>Tax</th><th>Stripe price</th><th>Actions</th></tr></thead><tbody><tr v-for="o in data.offers" :key="o.id"><td>{{o.plan_code==='plus'?'Collector Plus':'Collector'}}</td><td>{{money(o.total_minor)}} / {{o.cadence==='MONTHLY'?'month':'year'}}</td><td>{{money(o.tax_minor)}}</td><td><code>{{o.price_id}}</code></td><td><div class="button-row"><button class="button secondary" :disabled="busy" @click="publish(o)">{{o.published?'Pause':'Verify & publish'}}</button><button v-if="o.can_delete" type="button" class="button danger" :disabled="busy" @click="deleteOffer(o)">Delete draft</button></div></td></tr></tbody></table></div><p v-if="!data.offers.length" class="muted">No Stripe offers yet. Load a recurring price to create your first offer.</p></section>
<section v-if="data" class="panel settings-panel spaced"><h2>Subscription health</h2><div class="membership-table-wrap"><table><thead><tr><th>Account</th><th>State</th><th>Paid through</th><th>Last sync</th><th>Actions</th></tr></thead><tbody><tr v-for="s in data.subscriptions" :key="s.id"><td>{{s.email}}<small class="stripe-message">{{s.last_error}}</small></td><td>{{s.status}}<br><small v-if="s.cancel_at_period_end">Renewal cancelled</small></td><td>{{date(s.paid_through)}}</td><td>{{date(s.synced_at)}}</td><td><button class="button secondary" :disabled="busy" @click="run(()=>api(path('subscriptions/'+s.id+'/sync'),{method:'POST',body:{}}),'Payment state refreshed.')">Reconcile</button><button v-if="s.current&&!s.cancel_at_period_end" class="button secondary" :disabled="busy" @click="cancel(s)">Cancel</button></td></tr></tbody></table></div><p v-if="!data.subscriptions.length" class="muted">No Stripe checkout requests in this environment.</p><h3 class="spaced">Webhook queue</h3><p v-if="!data.events.length" class="muted">No outstanding events.</p><div v-for="e in data.events" :key="e.event_id" class="membership-history"><div><strong>{{e.event_type}}</strong><p class="small">{{e.status}} · {{e.last_error}}</p></div><button class="button secondary" :disabled="busy" @click="run(()=>api(path('events/'+e.event_id),{method:'POST',body:{}}),'Event queued for reconciliation.')">Retry</button></div></section>
</main></template>
<style src="~/assets/css/membership.css"></style>
<style scoped>.stripe-two{display:grid;grid-template-columns:1fr 1fr;gap:16px}.stripe-message{display:block;max-width:320px;white-space:normal}.stripe-admin code{overflow-wrap:anywhere}.stripe-admin .membership-status-grid strong{overflow-wrap:anywhere}@media(max-width:680px){.stripe-two{grid-template-columns:1fr}.stripe-admin .page-heading{display:block}.stripe-admin .page-heading .button-row{margin-top:16px}}</style>
