<script setup lang="ts">
import { resolvedAppearance } from '../../../shared/appearance.mjs'
definePageMeta({ layout: 'bare' })
const route = useRoute(), api = useApi(), binder = ref<any>(null), error = ref(''), page = ref(0)
onMounted(async () => { try { binder.value = await api('/api/shared/' + route.params.token) } catch (e) { error.value = errorMessage(e) } })
const appearance = computed(() => resolvedAppearance(binder.value?.appearance, binder.value?.color))
const size = computed(() => binder.value ? binder.value.columns * binder.value.rows : 9)
const slots = computed<Record<number, any>>(() => Object.fromEntries((binder.value?.slots || []).map((s: any) => [s.position, s])))
</script>
<template><header class="shared-header"><NuxtLink to="/" class="brand"><img src="/icon.svg" alt="" /><span>CardShelf</span></NuxtLink><span class="badge">{{ binder?.binder_type === 'tracking' ? 'Read-only tracking checklist' : 'Read-only binder plan' }}</span></header><p v-if="error" class="alert error">{{ error }}</p><div v-else-if="!binder" class="loading-panel">Loading shared binder…</div><div v-else class="shared-content"><header class="page-heading"><div><span class="eyebrow">SHARED WITH YOU</span><h1>{{ binder.title }}</h1><p>{{ binder.description }}</p></div></header><TrackingBinder v-if="binder.binder_type === 'tracking'" :binder="binder" read-only /><template v-else><BinderSurface class="single-page" :binder="binder" :share-token="String(route.params.token)"><div class="binder-page"><div class="binder-page-heading"><span>PAGE {{ page + 1 }}</span><small>{{ size }} pockets</small></div><div class="pocket-grid" :style="{ gridTemplateColumns: 'repeat(' + binder.columns + ', minmax(0, 1fr))' }"><div v-for="i in size" :key="i" class="pocket" :class="{ filled: slots[page * size + i - 1] }"><template v-if="slots[page * size + i - 1]"><CardArtwork :card="slots[page * size + i - 1]" :printing="slots[page * size + i - 1]" :effects-mode="String(appearance.effects_mode)" /><span class="pocket-caption">{{ slots[page * size + i - 1].label }}</span></template><small v-else>Empty pocket</small></div></div></div></BinderSurface><div class="binder-pagination"><button class="button secondary" :disabled="page <= 0" @click="page--"><AppIcon name="left" />Previous</button><span>{{ page + 1 }} / {{ binder.page_count }}</span><button class="button secondary" :disabled="page + 1 >= binder.page_count" @click="page++">Next<AppIcon name="right" /></button></div><p class="data-note">A planned layout does not establish ownership, condition, availability or a sale offer. Collection quantities and private notes are not shared.</p></template></div></template>
