<script setup lang="ts">
import { resolvedAppearance } from '../../../shared/appearance.mjs'
definePageMeta({ layout: 'bare' })
const route = useRoute(), api = useApi(), binder = ref<any>(null), error = ref(''), missingOnly = ref(true), checklist = ref(false)
onMounted(async () => { try { binder.value = await api('/api/binders/' + route.params.id) } catch (e) { error.value = errorMessage(e) } })
const tracking = computed(() => binder.value?.binder_type === 'tracking')
const collected = (card: any) => tracking.value ? card.is_collected === true : card.owned
const printingLabel = (card: any) => tracking.value && binder.value?.generation?.options?.selection === 'designs' ? 'Any printing' : card.label
const printBackground = ref(false)
watch(binder, value => { printBackground.value = value?.binder_type !== 'tracking' && Boolean(resolvedAppearance(value?.appearance, value?.color).print_background); if (value?.binder_type === 'tracking') checklist.value = true })
const cards = computed(() => (binder.value?.slots || []).filter((s: any) => !missingOnly.value || !collected(s)))
const sheets = computed(() => Array.from({ length: Math.ceil(cards.value.length / 9) }, (_, i) => cards.value.slice(i * 9, i * 9 + 9)))
function print() { window.print() }
</script>
<template><div class="no-print print-controls"><NuxtLink :to="'/binders/' + route.params.id" class="text-button"><AppIcon name="left" />Back to binder</NuxtLink><h1>{{ tracking ? 'Print checklist' : 'Print placeholders' }}</h1><p>{{ binder?.title }}</p><div class="button-row"><label class="checkbox-label"><input v-model="missingOnly" type="checkbox" />{{ tracking ? 'Missing cards only' : 'Missing printings only' }}</label><label class="checkbox-label"><input v-model="checklist" type="checkbox" />Checklist instead of cards</label><label v-if="!tracking" class="checkbox-label"><input v-model="printBackground" type="checkbox" :disabled="checklist" />Binder background</label><button class="button primary" :disabled="!cards.length" @click="print"><AppIcon name="print" />Print / save as PDF</button></div><p class="data-note">Placeholder dimensions: 63 × 88 mm; nine per A4 sheet. Use 100% scale, turn off browser headers/footers, and check your printer’s printable margins. Background graphics may need enabling in the browser print dialogue; untick Binder background for printer-friendly output.</p><p v-if="!cards.length && binder" class="alert info">There are no cards to print with these filters.</p></div><p v-if="error" class="alert error">{{ error }}</p><section v-if="checklist" class="print-checklist"><h2>{{ binder?.title }} — checklist</h2><table><thead><tr><th>Done</th><th>Card</th><th>Set / no.</th><th>Printing</th><th>Page / pocket</th></tr></thead><tbody><tr v-for="card in cards" :key="card.position"><td>{{ tracking && collected(card) ? '☑' : '□' }}</td><td>{{ card.name }}</td><td>{{ card.set_name }} / {{ card.local_id }}</td><td>{{ printingLabel(card) }}</td><td>{{ Math.floor(card.position / (binder.columns * binder.rows)) + 1 }} / {{ card.position % (binder.columns * binder.rows) + 1 }}</td></tr></tbody></table></section><div v-else class="print-sheets"><section v-for="(sheet, i) in sheets" :key="i" class="print-sheet" :class="{ 'has-background': printBackground }"><BinderWallpaper v-if="printBackground" :binder="binder" /><article v-for="card in sheet" :key="card.position" class="placeholder-card"><span class="placeholder-kicker">COLLECTION PLACEHOLDER</span><div><h2>{{ card.name }}</h2><p>{{ card.set_name }}</p><strong>#{{ card.local_id }} · {{ card.language.toUpperCase() }}</strong><p class="placeholder-printing">{{ printingLabel(card) }}</p></div><footer><span>{{ binder?.title }}</span><span>Page {{ Math.floor(card.position / (binder.columns * binder.rows)) + 1 }} · Pocket {{ card.position % (binder.columns * binder.rows) + 1 }}</span><small>CardShelf · {{ collected(card) ? (tracking ? 'Marked collected' : 'Owned printing') : 'Still to collect' }}</small></footer></article></section></div></template>
